import type { Language } from "./src/i18n"

type AnimeItem = {
  titleZh: string
  titleEn: string
  titleJa: string
  score: number
}

type Data = {
  [key: string]: AnimeItem[]
}

const data: Data = {
  "2006": [
    { titleZh: "死亡筆記本", titleEn: "Death Note", titleJa: "DEATH NOTE", score: 8.4 },
    { titleZh: "Code Geass 反叛的魯路修", titleEn: "Code Geass: Lelouch of the Rebellion", titleJa: "コードギアス 反逆のルルーシュ", score: 8.5 },
    { titleZh: "銀魂", titleEn: "Gintama", titleJa: "銀魂", score: 8.5 },
    { titleZh: "櫻蘭高校男公關部", titleEn: "Ouran High School Host Club", titleJa: "桜蘭高校ホスト部", score: 8.1 },
    { titleZh: "BLACK LAGOON 黑礁", titleEn: "Black Lagoon", titleJa: "BLACK LAGOON", score: 7.8 },
    { titleZh: "NANA", titleEn: "NANA", titleJa: "NANA-ナナ-", score: 8.5 },
    { titleZh: "涼宮春日的憂鬱", titleEn: "The Melancholy of Haruhi Suzumiya", titleJa: "涼宮ハルヒの憂鬱", score: 7.6 },
    { titleZh: "歡迎加入N.H.K.！", titleEn: "Welcome to the N-H-K", titleJa: "N・H・Kにようこそ！", score: 8.2 },
    { titleZh: "Fate/stay night", titleEn: "Fate/stay night", titleJa: "Fate/stay night", score: 6.8 },
    { titleZh: "暮蟬悲鳴時", titleEn: "When They Cry", titleJa: "ひぐらしのなく頃に", score: 7.5 },
    { titleZh: "死亡代理人", titleEn: "Ergo Proxy", titleJa: "Ergo Proxy", score: 7.6 },
    { titleZh: "零之使魔", titleEn: "The Familiar of Zero", titleJa: "ゼロの使い魔", score: 6.8 },
    { titleZh: "驅魔少年 D.Gray-man", titleEn: "D.Gray-man", titleJa: "ディー・グレイマン", score: 7.6 },
    { titleZh: "家庭教師HITMAN REBORN!", titleEn: "REBORN!", titleJa: "家庭教師ヒットマンREBORN!", score: 7.7 },
    { titleZh: "×××HOLiC", titleEn: "xxxHOLiC", titleJa: "XXX ホリック", score: 7.6 },
  ],
  "2007": [
    { titleZh: "火影忍者 疾風傳", titleEn: "Naruto: Shippuden", titleJa: "NARUTO -ナルト- 疾風伝", score: 8.2 },
    { titleZh: "天元突破 紅蓮螺巖", titleEn: "Gurren Lagann", titleJa: "天元突破グレンラガン", score: 8.5 },
    { titleZh: "CLANNAD", titleEn: "Clannad", titleJa: "ＣＬＡＮＮＡＤ -クラナド-", score: 7.7 },
    { titleZh: "BACCANO! 大騷動！", titleEn: "Baccano!", titleJa: "バッカーノ！", score: 8.1 },
    { titleZh: "DARKER THAN BLACK 黑之契約者", titleEn: "Darker than Black", titleJa: "DARKER THAN BLACK -黒の契約者-", score: 7.7 },
    { titleZh: "幸運☆星", titleEn: "Lucky☆Star", titleJa: "らき☆すた", score: 7.5 },
    { titleZh: "戀愛情結", titleEn: "Lovely Complex", titleJa: "ラブ★コン", score: 7.8 },
    { titleZh: "School Days", titleEn: "School Days (TV)", titleJa: "School Days (TV)", score: 4.9 },
    { titleZh: "大劍 CLAYMORE", titleEn: "Claymore", titleJa: "CLAYMORE", score: 7.4 },
    { titleZh: "賭博默示錄", titleEn: "Kaiji - Ultimate Survivor", titleJa: "逆境無頼カイジ Ultimate Survivor", score: 8.2 },
    { titleZh: "物怪", titleEn: "Mononoke", titleJa: "モノノ怪", score: 8.2 },
    { titleZh: "暮蟬悲鳴時 解", titleEn: "When They Cry Kai", titleJa: "ひぐらしのなく頃に解", score: 8 },
    { titleZh: "零之使魔～雙月騎士～", titleEn: "The Familiar of Zero: Knight of the Twin Moons", titleJa: "ゼロの使い魔 ～双月の騎士～", score: 7 },
    { titleZh: "爆炸頭武士", titleEn: "Afro Samurai", titleJa: "アフロサムライ", score: 7.1 },
    { titleZh: "再見、絕望老師", titleEn: "Sayonara, Zetsubou-Sensei", titleJa: "さよなら絶望先生", score: 7.6 },
  ],
  "2008": [
    { titleZh: "龍與虎 TIGER×DRAGON！", titleEn: "Toradora!", titleJa: "とらドラ！", score: 7.8 },
    { titleZh: "Soul Eater 噬魂者", titleEn: "Soul Eater", titleJa: "ソウルイーター", score: 7.7 },
    { titleZh: "Code Geass 反叛的魯路修 R2", titleEn: "Code Geass: Lelouch of the Rebellion R2", titleJa: "コードギアス 反逆のルルーシュ R2", score: 8.7 },
    { titleZh: "黑執事", titleEn: "Black Butler", titleJa: "黒執事", score: 7.3 },
    { titleZh: "CLANNAD ～AFTER STORY～", titleEn: "Clannad: After Story", titleJa: "ＣＬＡＮＮＡＤ ~After Story~ クラナド アフターストーリー", score: 8.8 },
    { titleZh: "魔法禁書目錄", titleEn: "A Certain Magical Index", titleJa: "とある魔術の禁書目録", score: 7 },
    { titleZh: "狼與辛香料", titleEn: "Spice and Wolf", titleJa: "狼と香辛料", score: 8 },
    { titleZh: "出包王女", titleEn: "To Love Ru", titleJa: "To LOVEる -とらぶる-", score: 6.5 },
    { titleZh: "夏目友人帳", titleEn: "Natsume's Book of Friends Season 1", titleJa: "夏目友人帳", score: 8 },
    { titleZh: "十字架與吸血姬", titleEn: "Rosario + Vampire", titleJa: "ロザリオとバンパイア", score: 6.3 },
    { titleZh: "吸血鬼騎士", titleEn: "Vampire Knight", titleJa: "ヴァンパイア騎士", score: 6.3 },
    { titleZh: "零之使魔～三美姬的輪舞～", titleEn: "The Familiar of Zero: \"Rondo\" of Princesses", titleJa: "ゼロの使い魔 ～三美姫（プリンセッセ）の輪舞（ロンド）～", score: 6.9 },
    { titleZh: "鶺鴒女神", titleEn: "Sekirei", titleJa: "セキレイ", score: 6.5 },
    { titleZh: "S.A 特優生", titleEn: "S.A: Special A", titleJa: "スペシャル・エー", score: 7.1 },
    { titleZh: "閃電十一人", titleEn: "Inazuma Eleven", titleJa: "イナズマイレブン", score: 7.6 },
  ],
  "2009": [
    { titleZh: "鋼之鍊金術師 FULLMETAL ALCHEMIST", titleEn: "Fullmetal Alchemist: Brotherhood", titleJa: "鋼の錬金術師 FULLMETAL ALCHEMIST", score: 9 },
    { titleZh: "魔導少年 FAIRY TAIL", titleEn: "Fairy Tail", titleJa: "FAIRY TAIL", score: 7.2 },
    { titleZh: "化物語", titleEn: "Bakemonogatari", titleJa: "化物語", score: 8.2 },
    { titleZh: "K-ON！輕音部", titleEn: "K-ON!", titleJa: "けいおん!", score: 7.8 },
    { titleZh: "好想告訴你", titleEn: "Kimi ni Todoke: From Me to You", titleJa: "君に届け", score: 7.9 },
    { titleZh: "科學超電磁砲", titleEn: "A Certain Scientific Railgun", titleJa: "とある科学の超電磁砲", score: 7.5 },
    { titleZh: "涼宮春日的憂鬱（2009）", titleEn: "The Melancholy of Haruhi Suzumiya (2009)", titleJa: "涼宮ハルヒの憂鬱", score: 7.1 },
    { titleZh: "東之伊甸", titleEn: "Eden of the East", titleJa: "東のエデン", score: 7.4 },
    { titleZh: "狼與辛香料II", titleEn: "Spice and Wolf II", titleJa: "狼と香辛料II", score: 8.1 },
    { titleZh: "七龍珠改", titleEn: "Dragon Ball Z Kai", titleJa: "ドラゴンボール改", score: 7.7 },
    { titleZh: "天降之物", titleEn: "Heaven's Lost Property", titleJa: "そらのおとしもの", score: 6.7 },
    { titleZh: "潘朵拉之心", titleEn: "PandoraHearts", titleJa: "パンドラハーツ", score: 7.2 },
    { titleZh: "東京地震8.0", titleEn: "Tokyo Magnitude 8.0", titleJa: "東京マグニチュード8.0", score: 7.7 },
    { titleZh: "DARKER THAN BLACK 流星的雙子", titleEn: "Darker than Black: Gemini of the Meteor", titleJa: "DARKER THAN BLACK -流星の双子-", score: 7.1 },
    { titleZh: "幻靈鎮魂曲", titleEn: "Phantom: Requiem for the Phantom", titleJa: "Phantom 〜Requiem for the Phantom〜", score: 7.5 },
  ],
  "2010": [
    { titleZh: "Angel Beats!", titleEn: "Angel Beats!", titleJa: "Angel Beats!", score: 7.7 },
    { titleZh: "無頭騎士異聞錄 DuRaRaRa!!", titleEn: "Durarara!!", titleJa: "デュラララ!!", score: 7.9 },
    { titleZh: "會長是女僕大人！", titleEn: "Maid-Sama!", titleJa: "会長はメイド様!", score: 7.8 },
    { titleZh: "學園默示錄 HIGHSCHOOL OF THE DEAD", titleEn: "High School of the Dead", titleJa: "学園黙示録HIGHSCHOOL OF THE DEAD", score: 6.7 },
    { titleZh: "K-ON！！輕音部", titleEn: "K-ON! Season 2", titleJa: "けいおん!!", score: 8.2 },
    { titleZh: "我的妹妹哪有這麼可愛！", titleEn: "Oreimo", titleJa: "俺の妹がこんなに可愛いわけがない", score: 6.5 },
    { titleZh: "刀語", titleEn: "Katanagatari", titleJa: "刀語", score: 8.1 },
    { titleZh: "只有神知道的世界", titleEn: "The World God Only Knows", titleJa: "神のみぞ知るセカイ", score: 7.4 },
    { titleZh: "屍鬼", titleEn: "Shiki", titleJa: "屍鬼", score: 7.5 },
    { titleZh: "爆漫王。", titleEn: "Bakuman.", titleJa: "バクマン。", score: 7.9 },
    { titleZh: "笨蛋、測驗、召喚獸", titleEn: "Baka and Test - Summon the Beasts", titleJa: "バカとテストと召喚獣", score: 7.1 },
    { titleZh: "妄想學生會", titleEn: "Seitokai Yakuindomo", titleJa: "生徒会役員共", score: 7.3 },
    { titleZh: "黑執事II", titleEn: "Black Butler II", titleJa: "黒執事II", score: 6.7 },
    { titleZh: "魔法禁書目錄II", titleEn: "A Certain Magical Index II", titleJa: "とある魔術の禁書目録II", score: 7.3 },
    { titleZh: "WORKING!!迷糊餐廳", titleEn: "Wagnaria!!", titleJa: "WORKING!!", score: 7.4 },
  ],
  "2011": [
    { titleZh: "HUNTER×HUNTER 獵人（2011）", titleEn: "Hunter x Hunter (2011)", titleJa: "HUNTER×HUNTER (2011)", score: 8.9 },
    { titleZh: "命運石之門", titleEn: "Steins;Gate", titleJa: "シュタインズ・ゲート", score: 8.9 },
    { titleZh: "青之驅魔師", titleEn: "Blue Exorcist", titleJa: "青の祓魔師", score: 7.2 },
    { titleZh: "未來日記", titleEn: "The Future Diary", titleJa: "未来日記", score: 6.9 },
    { titleZh: "我們仍未知道那天所看見的花的名字。", titleEn: "Anohana: The Flower We Saw That Day", titleJa: "あの日見た花の名前を僕達はまだ知らない。", score: 8 },
    { titleZh: "Fate/Zero", titleEn: "Fate/Zero", titleJa: "Fate/Zero", score: 8.1 },
    { titleZh: "魔法少女小圓", titleEn: "Puella Magi Madoka Magica", titleJa: "魔法少女まどか☆マギカ", score: 8.3 },
    { titleZh: "死囚樂園", titleEn: "Deadman Wonderland", titleJa: "デッドマン・ワンダーランド", score: 6.7 },
    { titleZh: "罪惡王冠", titleEn: "Guilty Crown", titleJa: "ギルティクラウン", score: 6.9 },
    { titleZh: "日常", titleEn: "Nichijou - My Ordinary Life", titleJa: "日常", score: 8.3 },
    { titleZh: "我的朋友很少", titleEn: "Haganai", titleJa: "僕は友達が少ない", score: 6.8 },
    { titleZh: "IS〈Infinite Stratos〉", titleEn: "Infinite Stratos", titleJa: "IS〈インフィニット・ストラトス〉", score: 6.1 },
    { titleZh: "GOSICK", titleEn: "Gosick", titleJa: "GOSICK", score: 7.7 },
    { titleZh: "花牌情緣", titleEn: "Chihayafuru", titleJa: "ちはやふる", score: 8 },
    { titleZh: "好想告訴你 2ND SEASON", titleEn: "Kimi ni Todoke: From Me to You Season 2", titleJa: "君に届け 2ND SEASON", score: 7.9 },
  ],
  "2012": [
    { titleZh: "Sword Art Online 刀劍神域", titleEn: "Sword Art Online", titleJa: "ソードアート・オンライン", score: 7 },
    { titleZh: "JoJo的奇妙冒險（TV）", titleEn: "JoJo's Bizarre Adventure (TV)", titleJa: "ジョジョの奇妙な冒険 (TV)", score: 7.7 },
    { titleZh: "Another 替身", titleEn: "Another", titleJa: "アナザー", score: 7.1 },
    { titleZh: "PSYCHO-PASS 心靈判官", titleEn: "PSYCHO-PASS", titleJa: "PSYCHO-PASS サイコパス", score: 8.1 },
    { titleZh: "冰菓", titleEn: "Hyouka", titleJa: "氷菓", score: 7.9 },
    { titleZh: "中二病也想談戀愛！", titleEn: "Love, Chunibyo & Other Delusions", titleJa: "中二病でも恋がしたい!", score: 7.6 },
    { titleZh: "惡魔高校D×D", titleEn: "High School DxD", titleJa: "ハイスクールD×D", score: 6.9 },
    { titleZh: "影子籃球員", titleEn: "Kuroko's Basketball", titleJa: "黒子のバスケ", score: 7.8 },
    { titleZh: "櫻花莊的寵物女孩", titleEn: "The Pet Girl of Sakurasou", titleJa: "さくら荘のペットな彼女", score: 7.8 },
    { titleZh: "鄰家的怪同學", titleEn: "My Little Monster", titleJa: "となりの怪物くん", score: 7.2 },
    { titleZh: "Fate/Zero 第二季", titleEn: "Fate/Zero Season 2", titleJa: "Fate/Zero 2ndシーズン", score: 8.4 },
    { titleZh: "魔奇少年 MAGI", titleEn: "Magi: The Labyrinth of Magic", titleJa: "マギ The labyrinth of magic", score: 7.8 },
    { titleZh: "男子高中生的日常", titleEn: "Daily Lives of High School Boys", titleJa: "男子高校生の日常", score: 8 },
    { titleZh: "Kokoro Connect 心靈連結", titleEn: "Kokoro Connect", titleJa: "ココロコネクト", score: 7.5 },
    { titleZh: "偽物語", titleEn: "Nisemonogatari", titleJa: "偽物語", score: 7.9 },
  ],
  "2013": [
    { titleZh: "進擊的巨人", titleEn: "Attack on Titan", titleJa: "進撃の巨人", score: 8.5 },
    { titleZh: "KILL la KILL", titleEn: "Kill la Kill", titleJa: "キルラキル", score: 7.9 },
    { titleZh: "打工吧！魔王大人", titleEn: "The Devil is a Part-Timer!", titleJa: "はたらく魔王さま!", score: 7.5 },
    { titleZh: "果然我的青春戀愛喜劇搞錯了。", titleEn: "My Teen Romantic Comedy SNAFU", titleJa: "やはり俺の青春ラブコメはまちがっている。", score: 7.8 },
    { titleZh: "境界的彼方", titleEn: "Beyond the Boundary", titleJa: "境界の彼方", score: 7.4 },
    { titleZh: "Golden Time", titleEn: "Golden Time", titleJa: "ゴールデンタイム", score: 7.5 },
    { titleZh: "約會大作戰 DATE A LIVE", titleEn: "Date A Live", titleJa: "デート・ア・ライブ", score: 6.8 },
    { titleZh: "記錄的地平線", titleEn: "Log Horizon", titleJa: "ログ・ホライズン", score: 7.6 },
    { titleZh: "槍彈辯駁 希望的學園與絕望的高中生 The Animation", titleEn: "Danganronpa: The Animation", titleJa: "ダンガンロンパ 希望の学園と絶望の高校生 The Animation", score: 6.9 },
    { titleZh: "惡魔高校D×D NEW", titleEn: "High School DxD NEW", titleJa: "ハイスクールD×D NEW", score: 7.1 },
    { titleZh: "Free！男子游泳部", titleEn: "Free! -Iwatobi Swim Club-", titleJa: "Free!", score: 7.2 },
    { titleZh: "影子籃球員 第二季", titleEn: "Kuroko's Basketball 2", titleJa: "黒子のバスケ 2nd SEASON", score: 8 },
    { titleZh: "物語系列 第二季", titleEn: "Monogatari Series Second Season", titleJa: "〈物語〉シリーズ セカンドシーズン", score: 8.8 },
    { titleZh: "魔奇少年 MAGI 王國", titleEn: "Magi: The Kingdom of Magic", titleJa: "マギ The kingdom of magic", score: 8.1 },
    { titleZh: "我不受歡迎，怎麼想都是你們的錯！", titleEn: "WataMote: No Matter How I Look At It, It's You Guys' Fault I'm Not Popular!", titleJa: "私がモテないのはどう考えてもお前らが悪い!", score: 6.7 },
  ],
  "2014": [
    { titleZh: "東京喰種", titleEn: "Tokyo Ghoul", titleJa: "東京喰種 トーキョーグール", score: 7.6 },
    { titleZh: "四月是你的謊言", titleEn: "Your lie in April", titleJa: "四月は君の嘘", score: 8.4 },
    { titleZh: "排球少年!!", titleEn: "HAIKYU!!", titleJa: "ハイキュー!!", score: 8.4 },
    { titleZh: "NO GAME NO LIFE 遊戲人生", titleEn: "No Game, No Life", titleJa: "ノーゲーム・ノーライフ", score: 7.7 },
    { titleZh: "流浪神差", titleEn: "Noragami", titleJa: "ノラガミ", score: 7.8 },
    { titleZh: "斬！赤紅之瞳", titleEn: "Akame ga Kill!", titleJa: "アカメが斬る！", score: 7.3 },
    { titleZh: "七大罪", titleEn: "The Seven Deadly Sins", titleJa: "七つの大罪", score: 7.3 },
    { titleZh: "寄生獸 生命的準則", titleEn: "Parasyte -the maxim-", titleJa: "寄生獣 セイの格率", score: 8.1 },
    { titleZh: "Sword Art Online 刀劍神域 II", titleEn: "Sword Art Online II", titleJa: "ソードアート・オンライン II", score: 6.6 },
    { titleZh: "JoJo的奇妙冒險 星塵鬥士", titleEn: "JoJo's Bizarre Adventure: Stardust Crusaders", titleJa: "ジョジョの奇妙な冒険 スターダストクルセイダース", score: 7.9 },
    { titleZh: "殘響的恐怖", titleEn: "Terror in Resonance", titleJa: "残響のテロル", score: 7.8 },
    { titleZh: "偽戀", titleEn: "Nisekoi", titleJa: "ニセコイ", score: 7.3 },
    { titleZh: "Fate/stay night [Unlimited Blade Works]", titleEn: "Fate/stay night: Unlimited Blade Works", titleJa: "Fate/stay night [Unlimited Blade Works]", score: 8 },
    { titleZh: "魔法科高中的劣等生", titleEn: "The Irregular at Magic High School", titleJa: "魔法科高校の劣等生", score: 7 },
    { titleZh: "青春之旅", titleEn: "Blue Spring Ride", titleJa: "アオハライド", score: 7.5 },
  ],
  "2015": [
    { titleZh: "ONE PUNCH MAN 一拳超人", titleEn: "One-Punch Man", titleJa: "ワンパンマン", score: 8.3 },
    { titleZh: "暗殺教室", titleEn: "Assassination Classroom", titleJa: "暗殺教室", score: 7.9 },
    { titleZh: "死亡遊行", titleEn: "Death Parade", titleJa: "デス・パレード", score: 8 },
    { titleZh: "Charlotte", titleEn: "Charlotte", titleJa: "Charlotte(シャーロット)", score: 7.5 },
    { titleZh: "東京喰種√A", titleEn: "Tokyo Ghoul √A", titleJa: "東京喰種[トーキョーグール]√A", score: 6.7 },
    { titleZh: "食戟之靈", titleEn: "Food Wars!", titleJa: "食戟のソーマ", score: 7.8 },
    { titleZh: "OVERLORD", titleEn: "Overlord", titleJa: "オーバーロード", score: 7.7 },
    { titleZh: "排球少年!! 第二季", titleEn: "HAIKYU!! 2nd Season", titleJa: "ハイキュー!! セカンドシーズン", score: 8.6 },
    { titleZh: "在地下城尋求邂逅是否搞錯了什麼", titleEn: "Is It Wrong to Try to Pick Up Girls in a Dungeon?", titleJa: "ダンジョンに出会いを求めるのは間違っているだろうか", score: 7.3 },
    { titleZh: "終結的熾天使", titleEn: "Seraph of the End: Vampire Reign", titleJa: "終わりのセラフ", score: 7.3 },
    { titleZh: "流浪神差 ARAGOTO", titleEn: "Noragami Aragoto", titleJa: "ノラガミ ARAGOTO", score: 8 },
    { titleZh: "JoJo的奇妙冒險 星塵鬥士 埃及篇", titleEn: "JoJo's Bizarre Adventure: Stardust Crusaders - Battle in Egypt", titleJa: "ジョジョの奇妙な冒険 スターダストクルセイダース エジプト編", score: 8.2 },
    { titleZh: "果然我的青春戀愛喜劇搞錯了。續", titleEn: "My Teen Romantic Comedy SNAFU TOO!", titleJa: "やはり俺の青春ラブコメはまちがっている。続", score: 8.1 },
    { titleZh: "可塑性記憶", titleEn: "Plastic Memories", titleJa: "プラスティックメモリーズ", score: 7.7 },
    { titleZh: "監獄學園", titleEn: "Prison School", titleJa: "監獄学園〈プリズンスクール〉", score: 7.3 },
  ],
  "2016": [
    { titleZh: "我的英雄學院", titleEn: "My Hero Academia", titleJa: "僕のヒーローアカデミア", score: 7.7 },
    { titleZh: "靈能百分百", titleEn: "Mob Psycho 100", titleJa: "モブサイコ100", score: 8.4 },
    { titleZh: "Re:從零開始的異世界生活", titleEn: "Re:ZERO -Starting Life in Another World-", titleJa: "Re:ゼロから始める異世界生活", score: 8.1 },
    { titleZh: "只有我不存在的城市", titleEn: "ERASED", titleJa: "僕だけがいない街", score: 8.1 },
    { titleZh: "為美好的世界獻上祝福！", titleEn: "KONOSUBA -God's blessing on this wonderful world!", titleJa: "この素晴らしい世界に祝福を！", score: 7.9 },
    { titleZh: "文豪Stray Dogs", titleEn: "Bungo Stray Dogs", titleJa: "文豪ストレイドッグス", score: 7.7 },
    { titleZh: "暗殺教室 第二季", titleEn: "Assassination Classroom Second Season", titleJa: "暗殺教室 第２期", score: 8.3 },
    { titleZh: "排球少年!! 烏野高中 VS 白鳥澤學園高中", titleEn: "HAIKYU!! 3rd Season", titleJa: "ハイキュー!! 烏野高校 VS 白鳥沢学園高校", score: 8.7 },
    { titleZh: "JoJo的奇妙冒險 不滅鑽石", titleEn: "JoJo's Bizarre Adventure: Diamond is Unbreakable", titleJa: "ジョジョの奇妙な冒険 ダイヤモンドは砕けない", score: 8.4 },
    { titleZh: "食戟之靈 貳之皿", titleEn: "Food Wars! The Second Plate", titleJa: "食戟のソーマ 弍ノ皿", score: 7.9 },
    { titleZh: "orange", titleEn: "Orange", titleJa: "orange", score: 7.5 },
    { titleZh: "Yuri!!! on ICE", titleEn: "Yuri!!! on ICE", titleJa: "ユーリ!!! on ICE", score: 7.8 },
    { titleZh: "3月的獅子", titleEn: "March comes in like a lion", titleJa: "３月のライオン", score: 8.3 },
    { titleZh: "羈絆者 KIZNAIVER", titleEn: "Kiznaiver", titleJa: "キズナイーバー", score: 7.2 },
    { titleZh: "91Days", titleEn: "91 Days", titleJa: "91Days", score: 7.6 },
  ],
  "2017": [
    { titleZh: "進擊的巨人 第二季", titleEn: "Attack on Titan Season 2", titleJa: "進撃の巨人 Season２", score: 8.5 },
    { titleZh: "我的英雄學院 第二季", titleEn: "My Hero Academia Season 2", titleJa: "僕のヒーローアカデミア２", score: 8 },
    { titleZh: "黑色五葉草", titleEn: "Black Clover", titleJa: "ブラッククローバー", score: 7.9 },
    { titleZh: "狂賭之淵", titleEn: "Kakegurui", titleJa: "賭ケグルイ", score: 7 },
    { titleZh: "歡迎來到實力至上主義的教室", titleEn: "Classroom of the Elite", titleJa: "ようこそ実力至上主義の教室へ", score: 7.6 },
    { titleZh: "來自深淵", titleEn: "Made in Abyss", titleJa: "メイドインアビス", score: 8.5 },
    { titleZh: "為美好的世界獻上祝福！2", titleEn: "KONOSUBA -God's blessing on this wonderful world! 2", titleJa: "この素晴らしい世界に祝福を！2", score: 8.1 },
    { titleZh: "小林家的龍女僕", titleEn: "Miss Kobayashi's Dragon Maid", titleJa: "小林さんちのメイドラゴン", score: 7.7 },
    { titleZh: "幼女戰記", titleEn: "Saga of Tanya the Evil", titleJa: "幼女戦記", score: 7.8 },
    { titleZh: "魔法使的新娘", titleEn: "The Ancient Magus' Bride", titleJa: "魔法使いの嫁", score: 7.8 },
    { titleZh: "政宗君的復仇", titleEn: "Masamune-kun's Revenge", titleJa: "政宗くんのリベンジ", score: 6.6 },
    { titleZh: "食戟之靈 餐之皿", titleEn: "Food Wars! The Third Plate", titleJa: "食戟のソーマ 餐ノ皿", score: 7.8 },
    { titleZh: "BORUTO-火影新世代-", titleEn: "Boruto: Naruto Next Generations", titleJa: "BORUTO-ボルト- NARUTO NEXT GENERATIONS", score: 5.7 },
    { titleZh: "不正經的魔術講師與禁忌教典", titleEn: "Akashic Records of Bastard Magic Instructor", titleJa: "ロクでなし魔術講師と禁忌教典(アカシックレコード)", score: 6.8 },
    { titleZh: "情色漫畫老師", titleEn: "Eromanga Sensei", titleJa: "エロマンガ先生", score: 6 },
  ],
  "2018": [
    { titleZh: "進擊的巨人 第三季", titleEn: "Attack on Titan Season 3", titleJa: "進撃の巨人 Season３", score: 8.6 },
    { titleZh: "我的英雄學院 第三季", titleEn: "My Hero Academia Season 3", titleJa: "僕のヒーローアカデミア３", score: 7.9 },
    { titleZh: "青春豬頭少年不會夢到兔女郎學姊", titleEn: "Rascal Does Not Dream of Bunny Girl Senpai", titleJa: "青春ブタ野郎はバニーガール先輩の夢を見ない", score: 8.1 },
    { titleZh: "紫羅蘭永恆花園", titleEn: "Violet Evergarden", titleJa: "ヴァイオレット・エヴァーガーデン", score: 8.5 },
    { titleZh: "DARLING in the FRANXX", titleEn: "DARLING in the FRANXX", titleJa: "ダーリン・イン・ザ・フランキス", score: 7 },
    { titleZh: "關於我轉生變成史萊姆這檔事", titleEn: "That Time I Got Reincarnated as a Slime", titleJa: "転生したらスライムだった件", score: 8 },
    { titleZh: "阿宅的戀愛太難", titleEn: "Wotakoi: Love is Hard for Otaku", titleJa: "ヲタクに恋は難しい", score: 7.8 },
    { titleZh: "BANANA FISH", titleEn: "BANANA FISH", titleJa: "BANANA FISH", score: 8.4 },
    { titleZh: "東京喰種:re", titleEn: "Tokyo Ghoul:re", titleJa: "東京喰種-トーキョーグール-:re", score: 6.2 },
    { titleZh: "哥布林殺手", titleEn: "GOBLIN SLAYER", titleJa: "ゴブリンスレイヤー", score: 7.1 },
    { titleZh: "JoJo的奇妙冒險 黃金之風", titleEn: "JoJo's Bizarre Adventure: Golden Wind", titleJa: "ジョジョの奇妙な冒険 黄金の風", score: 8.5 },
    { titleZh: "Sword Art Online 刀劍神域 Alicization", titleEn: "Sword Art Online: Alicization", titleJa: "ソードアート・オンライン アリシゼーション", score: 7.5 },
    { titleZh: "七大罪 戒律的復活", titleEn: "The Seven Deadly Sins: Revival of the Commandments", titleJa: "七つの大罪 戒めの復活", score: 7.3 },
    { titleZh: "OVERLORD II", titleEn: "Overlord II", titleJa: "オーバーロードⅡ", score: 7.6 },
    { titleZh: "GRAND BLUE 碧藍之海", titleEn: "Grand Blue Dreaming", titleJa: "ぐらんぶる", score: 8.2 },
  ],
  "2019": [
    { titleZh: "鬼滅之刃", titleEn: "Demon Slayer: Kimetsu no Yaiba", titleJa: "鬼滅の刃", score: 8.3 },
    { titleZh: "約定的夢幻島", titleEn: "The Promised Neverland", titleJa: "約束のネバーランド", score: 8.4 },
    { titleZh: "進擊的巨人 第三季 Part.2", titleEn: "Attack on Titan Season 3 Part 2", titleJa: "進撃の巨人 Season３ Part.2", score: 9 },
    { titleZh: "輝夜姬想讓人告白～天才們的戀愛頭腦戰～", titleEn: "Kaguya-sama: Love is War", titleJa: "かぐや様は告らせたい～天才たちの恋愛頭脳戦～", score: 8.3 },
    { titleZh: "Dr.STONE 新石紀", titleEn: "Dr. STONE", titleJa: "Dr.STONE", score: 8.1 },
    { titleZh: "海盜戰記 VINLAND SAGA", titleEn: "Vinland Saga", titleJa: "ヴィンランド・サガ", score: 8.7 },
    { titleZh: "我的英雄學院 第四季", titleEn: "My Hero Academia Season 4", titleJa: "僕のヒーローアカデミア４", score: 7.9 },
    { titleZh: "炎炎消防隊", titleEn: "Fire Force", titleJa: "炎炎ノ消防隊", score: 7.6 },
    { titleZh: "一拳超人 第二季", titleEn: "One-Punch Man Season 2", titleJa: "ワンパンマン 2", score: 7.4 },
    { titleZh: "盾之勇者成名錄", titleEn: "The Rising of the Shield Hero", titleJa: "盾の勇者の成り上がり", score: 7.7 },
    { titleZh: "靈能百分百 II", titleEn: "Mob Psycho 100 II", titleJa: "モブサイコ100 II", score: 8.7 },
    { titleZh: "多羅羅", titleEn: "Dororo", titleJa: "どろろ", score: 8.1 },
    { titleZh: "五等分的新娘", titleEn: "The Quintessential Quintuplets", titleJa: "五等分の花嫁", score: 7.6 },
    { titleZh: "Fruits Basket 幻影天使", titleEn: "Fruits Basket (2019)", titleJa: "フルーツバスケット 1st Season", score: 8.2 },
    { titleZh: "BEASTARS", titleEn: "BEASTARS", titleJa: "BEASTARS", score: 7.7 },
  ],
  "2020": [
    { titleZh: "咒術迴戰", titleEn: "JUJUTSU KAISEN", titleJa: "呪術廻戦", score: 8.4 },
    { titleZh: "輝夜姬想讓人告白？～天才們的戀愛頭腦戰～", titleEn: "Kaguya-sama: Love is War?", titleJa: "かぐや様は告らせたい？～天才たちの恋愛頭脳戦～", score: 8.5 },
    { titleZh: "Re:從零開始的異世界生活 第二季", titleEn: "Re:ZERO -Starting Life in Another World- Season 2", titleJa: "Re:ゼロから始める異世界生活 2nd Season", score: 8.3 },
    { titleZh: "神之塔 Tower of God", titleEn: "Tower of God", titleJa: "神之塔 -Tower of God-", score: 7.4 },
    { titleZh: "租借女友", titleEn: "Rent-a-Girlfriend", titleJa: "彼女、お借りします", score: 6.6 },
    { titleZh: "炎炎消防隊 貳之章", titleEn: "Fire Force Season 2", titleJa: "炎炎ノ消防隊 弐ノ章", score: 7.8 },
    { titleZh: "高校之神", titleEn: "The God of High School", titleJa: "THE GOD OF HIGH SCHOOL ゴッド・オブ・ハイスクール", score: 7 },
    { titleZh: "排球少年!! TO THE TOP", titleEn: "HAIKYU!! TO THE TOP", titleJa: "ハイキュー!! TO THE TOP", score: 8.3 },
    { titleZh: "魔王學院的不適任者～史上最強的魔王始祖、轉生就讀子孫們的學校～", titleEn: "The Misfit of Demon King Academy: History’s Strongest Demon King Reincarnates and Goes to School with His Descendants", titleJa: "魔王学院の不適合者 ～史上最強の魔王の始祖、転生して子孫たちの学校へ通う～", score: 7.2 },
    { titleZh: "總之就是非常可愛", titleEn: "TONIKAWA: Over The Moon For You", titleJa: "トニカクカワイイ", score: 7.7 },
    { titleZh: "地縛少年花子君", titleEn: "Toilet-bound Hanako-kun", titleJa: "地縛少年 花子くん", score: 7.8 },
    { titleZh: "果然我的青春戀愛喜劇搞錯了。完", titleEn: "My Teen Romantic Comedy SNAFU Climax!", titleJa: "やはり俺の青春ラブコメはまちがっている。完", score: 8.2 },
    { titleZh: "在地下城尋求邂逅是否搞錯了什麼 III", titleEn: "Is It Wrong to Try to Pick Up Girls in a Dungeon? III", titleJa: "ダンジョンに出会いを求めるのは間違っているだろうかⅢ", score: 7.4 },
    { titleZh: "Sword Art Online 刀劍神域 Alicization War of Underworld 最終章", titleEn: "Sword Art Online: Alicization - War of Underworld Part 2", titleJa: "ソードアート・オンライン アリシゼーション War of Underworld 最終章 (2nd Season)", score: 7.4 },
    { titleZh: "異獸魔都", titleEn: "Dorohedoro", titleJa: "ドロヘドロ", score: 7.9 },
  ],
  "2021": [
    { titleZh: "進擊的巨人 最終季", titleEn: "Attack on Titan Final Season", titleJa: "進撃の巨人 The Final Season", score: 8.7 },
    { titleZh: "堀與宮村", titleEn: "Horimiya", titleJa: "ホリミヤ", score: 8.1 },
    { titleZh: "東京復仇者", titleEn: "Tokyo Revengers", titleJa: "東京リベンジャーズ", score: 7.7 },
    { titleZh: "無職轉生～到了異世界就拿出真本事～", titleEn: "Mushoku Tensei: Jobless Reincarnation", titleJa: "無職転生 ～異世界行ったら本気だす～", score: 8.2 },
    { titleZh: "我的英雄學院 第五季", titleEn: "My Hero Academia Season 5", titleJa: "僕のヒーローアカデミア５", score: 7.3 },
    { titleZh: "鬼滅之刃 無限列車篇", titleEn: "Demon Slayer: Kimetsu no Yaiba Mugen Train Arc", titleJa: "鬼滅の刃 無限列車編 (TV)", score: 8.2 },
    { titleZh: "Dr.STONE 新石紀 STONE WARS", titleEn: "Dr. STONE: STONE WARS", titleJa: "Dr.STONE STONE WARS", score: 8.1 },
    { titleZh: "約定的夢幻島 第二季", titleEn: "The Promised Neverland Season 2", titleJa: "約束のネバーランド2", score: 5.2 },
    { titleZh: "古見同學是溝通魯蛇。", titleEn: "Komi Can’t Communicate", titleJa: "古見さんは、コミュ症です。", score: 7.6 },
    { titleZh: "致不滅的你", titleEn: "To Your Eternity", titleJa: "不滅のあなたへ", score: 8.1 },
    { titleZh: "關於我轉生變成史萊姆這檔事 第二季", titleEn: "That Time I Got Reincarnated as a Slime Season 2", titleJa: "転生したらスライムだった件 第2期", score: 8.3 },
    { titleZh: "86 -不存在的戰區-", titleEn: "86 EIGHTY-SIX", titleJa: "86－エイティシックス－", score: 8.3 },
    { titleZh: "Re:從零開始的異世界生活 第二季 後半", titleEn: "Re:ZERO -Starting Life in Another World- Season 2 Part 2", titleJa: "Re:ゼロから始める異世界生活 2nd Season Part 2", score: 8.4 },
    { titleZh: "WONDER EGG PRIORITY", titleEn: "WONDER EGG PRIORITY", titleJa: "ワンダーエッグ・プライオリティ", score: 7.4 },
    { titleZh: "別逗我了，長瀞同學", titleEn: "DON'T TOY WITH ME, MISS NAGATORO", titleJa: "イジらないで、長瀞さん", score: 6.9 },
  ],
  "2022": [
    { titleZh: "鏈鋸人", titleEn: "Chainsaw Man", titleJa: "チェンソーマン", score: 8.3 },
    { titleZh: "SPY×FAMILY 間諜家家酒", titleEn: "SPY x FAMILY", titleJa: "SPY×FAMILY", score: 8.3 },
    { titleZh: "鬼滅之刃 遊郭篇", titleEn: "Demon Slayer: Kimetsu no Yaiba Entertainment District Arc", titleJa: "鬼滅の刃 遊郭編", score: 8.6 },
    { titleZh: "進擊的巨人 最終季 Part 2", titleEn: "Attack on Titan Final Season Part 2", titleJa: "進撃の巨人 The Final Season Part 2", score: 8.6 },
    { titleZh: "戀上換裝娃娃", titleEn: "My Dress-Up Darling", titleJa: "その着せ替え人形は恋をする", score: 8 },
    { titleZh: "BLUE LOCK 藍色監獄", titleEn: "BLUE LOCK", titleJa: "ブルーロック", score: 8 },
    { titleZh: "我想成為影之強者！", titleEn: "The Eminence in Shadow", titleJa: "陰の実力者になりたくて！", score: 8.1 },
    { titleZh: "輝夜姬想讓人告白 -Ultra Romantic-", titleEn: "Kaguya-sama: Love is War -Ultra Romantic-", titleJa: "かぐや様は告らせたい-ウルトラロマンティック-", score: 8.9 },
    { titleZh: "徹夜之歌", titleEn: "Call of the Night", titleJa: "よふかしのうた", score: 7.9 },
    { titleZh: "我的英雄學院 第六季", titleEn: "My Hero Academia Season 6", titleJa: "僕のヒーローアカデミア６", score: 8.2 },
    { titleZh: "靈能百分百 III", titleEn: "Mob Psycho 100 III", titleJa: "モブサイコ100 Ⅲ", score: 8.7 },
    { titleZh: "孤獨搖滾！", titleEn: "BOCCHI THE ROCK!", titleJa: "ぼっち・ざ・ろっく！", score: 8.7 },
    { titleZh: "歡迎來到實力至上主義的教室 第二季", titleEn: "Classroom of the Elite Season 2", titleJa: "ようこそ実力至上主義の教室へ 2nd Season", score: 7.9 },
    { titleZh: "盾之勇者成名錄 第二季", titleEn: "The Rising of the Shield Hero Season 2", titleJa: "盾の勇者の成り上がり Season 2", score: 6.5 },
    { titleZh: "夏日重現", titleEn: "Summer Time Rendering", titleJa: "サマータイムレンダ", score: 8.3 },
  ],
  "2023": [
    { titleZh: "咒術迴戰 第二季", titleEn: "JUJUTSU KAISEN Season 2", titleJa: "呪術廻戦 第2期", score: 8.6 },
    { titleZh: "葬送的芙莉蓮", titleEn: "Frieren: Beyond Journey’s End", titleJa: "葬送のフリーレン", score: 9.1 },
    { titleZh: "鬼滅之刃 刀匠村篇", titleEn: "Demon Slayer: Kimetsu no Yaiba Swordsmith Village Arc", titleJa: "鬼滅の刃 刀鍛冶の里編", score: 8.1 },
    { titleZh: "地獄樂", titleEn: "Hell’s Paradise", titleJa: "地獄楽", score: 8 },
    { titleZh: "【我推的孩子】", titleEn: "Oshi No Ko", titleJa: "【推しの子】", score: 8.4 },
    { titleZh: "藥師少女的獨語", titleEn: "The Apothecary Diaries", titleJa: "薬屋のひとりごと", score: 8.8 },
    { titleZh: "MASHLE 魔法少年", titleEn: "MASHLE: MAGIC AND MUSCLES", titleJa: "マッシュル-MASHLE-", score: 7.6 },
    { titleZh: "海盜戰記 VINLAND SAGA 第二季", titleEn: "Vinland Saga Season 2", titleJa: "ヴィンランド・サガ SEASON2", score: 8.8 },
    { titleZh: "無職轉生 II ～到了異世界就拿出真本事～", titleEn: "Mushoku Tensei: Jobless Reincarnation Season 2", titleJa: "無職転生Ⅱ ～異世界行ったら本気だす～", score: 8.1 },
    { titleZh: "殭屍100～在成為殭屍前要做的100件事～", titleEn: "Zom 100: Bucket List of the Dead", titleJa: "ゾン100～ゾンビになるまでにしたい100のこと～", score: 7.6 },
    { titleZh: "SPY×FAMILY 間諜家家酒 第二季", titleEn: "SPY x FAMILY Season 2", titleJa: "SPY×FAMILY Season 2", score: 8 },
    { titleZh: "天國大魔境", titleEn: "Tengoku Daimakyo", titleJa: "天国大魔境", score: 8.1 },
    { titleZh: "Dr.STONE 新石紀 NEW WORLD", titleEn: "Dr. STONE New World", titleJa: "Dr.STONE NEW WORLD", score: 8.1 },
    { titleZh: "和山田談場Lv999的戀愛", titleEn: "My Love Story with Yamada-kun at Lv999", titleJa: "山田くんとLv999の恋をする", score: 7.7 },
    { titleZh: "我想成為影之強者！ 第二季", titleEn: "The Eminence in Shadow Season 2", titleJa: "陰の実力者になりたくて！ 2nd season", score: 8.2 },
  ],
  "2024": [
    { titleZh: "我獨自升級", titleEn: "Solo Leveling", titleJa: "俺だけレベルアップな件", score: 8.1 },
    { titleZh: "膽大黨", titleEn: "DAN DA DAN", titleJa: "ダンダダン", score: 8.3 },
    { titleZh: "怪獸8號", titleEn: "Kaiju No. 8", titleJa: "怪獣８号", score: 8.1 },
    { titleZh: "鬼滅之刃 柱訓練篇", titleEn: "Demon Slayer: Kimetsu no Yaiba Hashira Training Arc", titleJa: "鬼滅の刃 柱稽古編", score: 7.9 },
    { titleZh: "迷宮飯", titleEn: "Delicious in Dungeon", titleJa: "ダンジョン飯", score: 8.5 },
    { titleZh: "無職轉生 II ～到了異世界就拿出真本事～ 第2部分", titleEn: "Mushoku Tensei: Jobless Reincarnation Season 2 Part 2", titleJa: "無職転生Ⅱ ～異世界行ったら本気だす～ 第2クール", score: 8.3 },
    { titleZh: "不時輕聲地以俄語遮羞的鄰座艾莉同學", titleEn: "Alya Sometimes Hides Her Feelings in Russian", titleJa: "時々ボソッとロシア語でデレる隣のアーリャさん", score: 7.5 },
    { titleZh: "WIND BREAKER 防風少年", titleEn: "WIND BREAKER", titleJa: "WIND BREAKER", score: 7.7 },
    { titleZh: "Re:從零開始的異世界生活 第三季", titleEn: "Re:ZERO -Starting Life in Another World- Season 3", titleJa: "Re:ゼロから始める異世界生活 3rd season", score: 8.4 },
    { titleZh: "歡迎來到實力至上主義的教室 第三季", titleEn: "Classroom of the Elite Season 3", titleJa: "ようこそ実力至上主義の教室へ 3rd Season", score: 7.8 },
    { titleZh: "關於我轉生變成史萊姆這檔事 第三季", titleEn: "That Time I Got Reincarnated as a Slime Season 3", titleJa: "転生したらスライムだった件 第3期", score: 7.8 },
    { titleZh: "MASHLE 魔法少年 神覺者候補選拔考試篇", titleEn: "MASHLE: MAGIC AND MUSCLES Season 2", titleJa: "マッシュル-MASHLE- 神覚者候補選抜試験編", score: 7.8 },
    { titleZh: "我的英雄學院 第七季", titleEn: "My Hero Academia Season 7", titleJa: "僕のヒーローアカデミア 7", score: 8.2 },
    { titleZh: "為美好的世界獻上祝福！3", titleEn: "KONOSUBA -God's blessing on this wonderful world! 3", titleJa: "この素晴らしい世界に祝福を！３", score: 8.2 },
    { titleZh: "【我推的孩子】第二季", titleEn: "Oshi no Ko Season 2", titleJa: "【推しの子】第2期", score: 8.5 },
  ],
  "2025": [
    { titleZh: "我獨自升級 第二季 -Arise from the Shadow-", titleEn: "Solo Leveling Season 2 -Arise from the Shadow-", titleJa: "俺だけレベルアップな件 Season 2 -Arise from the Shadow-", score: 8.5 },
    { titleZh: "Gachiakuta", titleEn: "Gachiakuta", titleJa: "ガチアクタ", score: 8.2 },
    { titleZh: "膽大黨 第二季", titleEn: "DAN DA DAN Season 2", titleJa: "ダンダダン 第2期", score: 8.3 },
    { titleZh: "薰香花朵凜然綻放", titleEn: "The Fragrant Flower Blooms With Dignity", titleJa: "薫る花は凛と咲く", score: 8.5 },
    { titleZh: "藥師少女的獨語 第二季", titleEn: "The Apothecary Diaries Season 2", titleJa: "薬屋のひとりごと 第2期", score: 8.8 },
    { titleZh: "戀上換裝娃娃 第二季", titleEn: "My Dress-Up Darling Season 2", titleJa: "その着せ替え人形は恋をする Season 2", score: 8.2 },
    { titleZh: "一拳超人 第三季", titleEn: "One-Punch Man Season 3", titleJa: "ワンパンマン３", score: 5 },
    { titleZh: "怪獸8號 第二季", titleEn: "Kaiju No. 8 Season 2", titleJa: "怪獣８号 第２期", score: 7.8 },
    { titleZh: "光逝去的夏天", titleEn: "The Summer Hikaru Died", titleJa: "光が死んだ夏", score: 8.1 },
    { titleZh: "炎炎消防隊 參之章", titleEn: "Fire Force Season 3", titleJa: "炎炎ノ消防隊 参ノ章", score: 7.8 },
    { titleZh: "SPY×FAMILY 間諜家家酒 第三季", titleEn: "SPY x FAMILY Season 3", titleJa: "SPY×FAMILY Season 3", score: 8.2 },
    { titleZh: "我的英雄學院 最終季", titleEn: "My Hero Academia FINAL SEASON", titleJa: "僕のヒーローアカデミア FINAL SEASON", score: 8.7 },
    { titleZh: "LAZARUS 拉撒路", titleEn: "LAZARUS", titleJa: "ラザロ", score: 7 },
    { titleZh: "Dr.STONE 新石紀 SCIENCE FUTURE", titleEn: "Dr. STONE SCIENCE FUTURE", titleJa: "Dr.STONE SCIENCE FUTURE", score: 8.2 },
    { titleZh: "WIND BREAKER 防風少年 第二季", titleEn: "WIND BREAKER Season 2", titleJa: "WIND BREAKER Season 2", score: 7.7 },
  ],
}

export default data

export const getAnimeTitle = (anime: AnimeItem, language: Language): string => {
  if (language === "en") return anime.titleEn
  if (language === "ja") return anime.titleJa
  return anime.titleZh
}
