import type { Language } from "./src/i18n"

type AnimeItem = {
  titleZh: string
  titleEn: string
  titleJa: string
  image: string
  popularity: number
  isSequel: boolean
  score: number
}

type Data = {
  [key: string]: AnimeItem[]
}

const data: Data = {
  "2005": [
    { titleZh: "蟲師", titleEn: "MUSHI-SHI", titleJa: "蟲師", image: "covers/457.png", popularity: 188205, isSequel: false, score: 8.5 },
    { titleZh: "灼眼的夏娜", titleEn: "Shakugan no Shana", titleJa: "灼眼のシャナ", image: "covers/355.png", popularity: 94589, isSequel: false, score: 7 },
    { titleZh: "交響詩篇 EUREKA SEVEN", titleEn: "Eureka Seven", titleJa: "交響詩篇エウレカセブン", image: "covers/237.jpg", popularity: 86108, isSequel: false, score: 7.8 },
    { titleZh: "地獄少女", titleEn: "Hell Girl", titleJa: "地獄少女", image: "covers/228.jpg", popularity: 74735, isSequel: false, score: 7.1 },
    { titleZh: "BLOOD+", titleEn: "Blood+", titleJa: "BLOOD+", image: "covers/150.png", popularity: 64606, isSequel: false, score: 7.6 },
    { titleZh: "天國之吻", titleEn: "Paradise Kiss", titleJa: "パラダイス・キス", image: "covers/322.png", popularity: 60496, isSequel: false, score: 7.8 },
    { titleZh: "蜂蜜幸運草", titleEn: "Honey and Clover", titleJa: "ハチミツとクローバー", image: "covers/16.jpg", popularity: 57528, isSequel: false, score: 7.6 },
    { titleZh: "ARIA The ANIMATION", titleEn: "ARIA The ANIMATION", titleJa: "ARIA The ANIMATION", image: "covers/477.png", popularity: 54935, isSequel: false, score: 7.6 },
    { titleZh: "AIR", titleEn: "Air", titleJa: "AIR", image: "covers/101.jpg", popularity: 51165, isSequel: false, score: 6.8 },
    { titleZh: "黑貓 BLACK CAT", titleEn: "Black Cat", titleJa: "ブラックキャット", image: "covers/68.jpg", popularity: 41825, isSequel: false, score: 7.1 },
    { titleZh: "驚爆危機！The Second Raid", titleEn: "Full Metal Panic! The Second Raid", titleJa: "フルメタル パニック！The Second Raid", image: "covers/73.jpg", popularity: 40827, isSequel: true, score: 7.7 },
    { titleZh: "Tsubasa翼·年代記", titleEn: "Tsubasa RESERVoir CHRoNiCLE", titleJa: "ツバサ・クロニクル", image: "covers/177.png", popularity: 36958, isSequel: false, score: 7.1 },
    { titleZh: "草莓棉花糖", titleEn: "Strawberry Marshmallow", titleJa: "苺ましまろ", image: "covers/488.png", popularity: 35641, isSequel: false, score: 7.4 },
    { titleZh: "光速蒙面俠21", titleEn: "Eyeshield 21", titleJa: "アイシールド21", image: "covers/15.png", popularity: 33201, isSequel: false, score: 7.6 },
    { titleZh: "甲賀忍法帖 BASILISK", titleEn: "Basilisk", titleJa: "バジリスク 甲賀忍法帖", image: "covers/67.jpg", popularity: 32864, isSequel: false, score: 7.1 },
  ],
  "2006": [
    { titleZh: "死亡筆記本", titleEn: "Death Note", titleJa: "DEATH NOTE", image: "covers/1535.jpg", popularity: 923471, isSequel: false, score: 8.4 },
    { titleZh: "Code Geass 反叛的魯路修", titleEn: "Code Geass: Lelouch of the Rebellion", titleJa: "コードギアス 反逆のルルーシュ", image: "covers/1575.jpg", popularity: 479473, isSequel: false, score: 8.5 },
    { titleZh: "銀魂", titleEn: "Gintama", titleJa: "銀魂", image: "covers/918.jpg", popularity: 285999, isSequel: false, score: 8.5 },
    { titleZh: "櫻蘭高校男公關部", titleEn: "Ouran High School Host Club", titleJa: "桜蘭高校ホスト部", image: "covers/853.jpg", popularity: 249052, isSequel: false, score: 8.1 },
    { titleZh: "BLACK LAGOON 黑礁", titleEn: "Black Lagoon", titleJa: "BLACK LAGOON", image: "covers/889.png", popularity: 242843, isSequel: false, score: 7.8 },
    { titleZh: "NANA", titleEn: "NANA", titleJa: "NANA-ナナ-", image: "covers/877.png", popularity: 198685, isSequel: false, score: 8.5 },
    { titleZh: "涼宮春日的憂鬱", titleEn: "The Melancholy of Haruhi Suzumiya", titleJa: "涼宮ハルヒの憂鬱", image: "covers/849.png", popularity: 195001, isSequel: false, score: 7.6 },
    { titleZh: "歡迎加入N.H.K.！", titleEn: "Welcome to the N-H-K", titleJa: "N・H・Kにようこそ！", image: "covers/1210.jpg", popularity: 193733, isSequel: false, score: 8.2 },
    { titleZh: "Fate/stay night", titleEn: "Fate/stay night", titleJa: "Fate/stay night", image: "covers/356.png", popularity: 183881, isSequel: true, score: 6.8 },
    { titleZh: "暮蟬悲鳴時", titleEn: "When They Cry", titleJa: "ひぐらしのなく頃に", image: "covers/934.jpg", popularity: 172843, isSequel: false, score: 7.5 },
    { titleZh: "死亡代理人", titleEn: "Ergo Proxy", titleJa: "Ergo Proxy", image: "covers/790.jpg", popularity: 151946, isSequel: false, score: 7.6 },
    { titleZh: "零之使魔", titleEn: "The Familiar of Zero", titleJa: "ゼロの使い魔", image: "covers/1195.png", popularity: 151265, isSequel: false, score: 6.8 },
    { titleZh: "驅魔少年 D.Gray-man", titleEn: "D.Gray-man", titleJa: "ディー・グレイマン", image: "covers/1482.jpg", popularity: 114015, isSequel: false, score: 7.6 },
    { titleZh: "家庭教師HITMAN REBORN!", titleEn: "REBORN!", titleJa: "家庭教師ヒットマンREBORN!", image: "covers/1604.png", popularity: 94646, isSequel: false, score: 7.7 },
    { titleZh: "×××HOLiC", titleEn: "xxxHOLiC", titleJa: "XXX ホリック", image: "covers/861.png", popularity: 68972, isSequel: false, score: 7.6 },
  ],
  "2007": [
    { titleZh: "火影忍者 疾風傳", titleEn: "Naruto: Shippuden", titleJa: "NARUTO -ナルト- 疾風伝", image: "covers/1735.png", popularity: 587608, isSequel: true, score: 8.2 },
    { titleZh: "天元突破 紅蓮螺巖", titleEn: "Gurren Lagann", titleJa: "天元突破グレンラガン", image: "covers/2001.png", popularity: 364828, isSequel: false, score: 8.5 },
    { titleZh: "CLANNAD", titleEn: "Clannad", titleJa: "ＣＬＡＮＮＡＤ -クラナド-", image: "covers/2167.jpg", popularity: 289538, isSequel: false, score: 7.7 },
    { titleZh: "BACCANO! 大騷動！", titleEn: "Baccano!", titleJa: "バッカーノ！", image: "covers/2251.jpg", popularity: 186167, isSequel: false, score: 8.1 },
    { titleZh: "DARKER THAN BLACK 黑之契約者", titleEn: "Darker than Black", titleJa: "DARKER THAN BLACK -黒の契約者-", image: "covers/2025.png", popularity: 172347, isSequel: false, score: 7.7 },
    { titleZh: "幸運☆星", titleEn: "Lucky☆Star", titleJa: "らき☆すた", image: "covers/1887.png", popularity: 140697, isSequel: false, score: 7.5 },
    { titleZh: "戀愛情結", titleEn: "Lovely Complex", titleJa: "ラブ★コン", image: "covers/2034.png", popularity: 129894, isSequel: false, score: 7.8 },
    { titleZh: "School Days", titleEn: "School Days (TV)", titleJa: "School Days (TV)", image: "covers/2476.jpg", popularity: 123599, isSequel: false, score: 4.9 },
    { titleZh: "大劍 CLAYMORE", titleEn: "Claymore", titleJa: "CLAYMORE", image: "covers/1818.jpg", popularity: 116712, isSequel: false, score: 7.4 },
    { titleZh: "賭博默示錄", titleEn: "Kaiji - Ultimate Survivor", titleJa: "逆境無頼カイジ Ultimate Survivor", image: "covers/3002.jpg", popularity: 95666, isSequel: false, score: 8.2 },
    { titleZh: "物怪", titleEn: "Mononoke", titleJa: "モノノ怪", image: "covers/2246.jpg", popularity: 89874, isSequel: false, score: 8.2 },
    { titleZh: "暮蟬悲鳴時 解", titleEn: "When They Cry Kai", titleJa: "ひぐらしのなく頃に解", image: "covers/1889.jpg", popularity: 88267, isSequel: true, score: 8 },
    { titleZh: "零之使魔～雙月騎士～", titleEn: "The Familiar of Zero: Knight of the Twin Moons", titleJa: "ゼロの使い魔 ～双月の騎士～", image: "covers/1840.jpg", popularity: 85925, isSequel: true, score: 7 },
    { titleZh: "爆炸頭武士", titleEn: "Afro Samurai", titleJa: "アフロサムライ", image: "covers/1292.png", popularity: 84277, isSequel: false, score: 7.1 },
    { titleZh: "再見、絕望老師", titleEn: "Sayonara, Zetsubou-Sensei", titleJa: "さよなら絶望先生", image: "covers/2605.png", popularity: 80696, isSequel: false, score: 7.6 },
  ],
  "2008": [
    { titleZh: "龍與虎 TIGER×DRAGON！", titleEn: "Toradora!", titleJa: "とらドラ！", image: "covers/4224.jpg", popularity: 524360, isSequel: false, score: 7.8 },
    { titleZh: "Soul Eater 噬魂者", titleEn: "Soul Eater", titleJa: "ソウルイーター", image: "covers/3588.png", popularity: 377754, isSequel: false, score: 7.7 },
    { titleZh: "Code Geass 反叛的魯路修 R2", titleEn: "Code Geass: Lelouch of the Rebellion R2", titleJa: "コードギアス 反逆のルルーシュ R2", image: "covers/2904.jpg", popularity: 350413, isSequel: true, score: 8.7 },
    { titleZh: "黑執事", titleEn: "Black Butler", titleJa: "黒執事", image: "covers/4898.jpg", popularity: 253381, isSequel: false, score: 7.3 },
    { titleZh: "CLANNAD ～AFTER STORY～", titleEn: "Clannad: After Story", titleJa: "ＣＬＡＮＮＡＤ ~After Story~ クラナド アフターストーリー", image: "covers/4181.png", popularity: 217046, isSequel: true, score: 8.8 },
    { titleZh: "魔法禁書目錄", titleEn: "A Certain Magical Index", titleJa: "とある魔術の禁書目録", image: "covers/4654.jpg", popularity: 185728, isSequel: false, score: 7 },
    { titleZh: "狼與辛香料", titleEn: "Spice and Wolf", titleJa: "狼と香辛料", image: "covers/2966.png", popularity: 177255, isSequel: false, score: 8 },
    { titleZh: "出包王女", titleEn: "To Love Ru", titleJa: "To LOVEる -とらぶる-", image: "covers/3455.png", popularity: 136996, isSequel: false, score: 6.5 },
    { titleZh: "夏目友人帳", titleEn: "Natsume's Book of Friends Season 1", titleJa: "夏目友人帳", image: "covers/4081.jpg", popularity: 124788, isSequel: false, score: 8 },
    { titleZh: "十字架與吸血姬", titleEn: "Rosario + Vampire", titleJa: "ロザリオとバンパイア", image: "covers/2993.jpg", popularity: 121705, isSequel: false, score: 6.3 },
    { titleZh: "吸血鬼騎士", titleEn: "Vampire Knight", titleJa: "ヴァンパイア騎士", image: "covers/3457.jpg", popularity: 97835, isSequel: false, score: 6.3 },
    { titleZh: "零之使魔～三美姬的輪舞～", titleEn: "The Familiar of Zero: \"Rondo\" of Princesses", titleJa: "ゼロの使い魔 ～三美姫（プリンセッセ）の輪舞（ロンド）～", image: "covers/3712.jpg", popularity: 75473, isSequel: true, score: 6.9 },
    { titleZh: "鶺鴒女神", titleEn: "Sekirei", titleJa: "セキレイ", image: "covers/4063.png", popularity: 74842, isSequel: false, score: 6.5 },
    { titleZh: "S.A 特優生", titleEn: "S.A: Special A", titleJa: "スペシャル・エー", image: "covers/3470.jpg", popularity: 60069, isSequel: false, score: 7.1 },
    { titleZh: "閃電十一人", titleEn: "Inazuma Eleven", titleJa: "イナズマイレブン", image: "covers/5231.png", popularity: 59944, isSequel: false, score: 7.6 },
  ],
  "2009": [
    { titleZh: "鋼之鍊金術師 FULLMETAL ALCHEMIST", titleEn: "Fullmetal Alchemist: Brotherhood", titleJa: "鋼の錬金術師 FULLMETAL ALCHEMIST", image: "covers/5114.jpg", popularity: 701910, isSequel: false, score: 9 },
    { titleZh: "魔導少年 FAIRY TAIL", titleEn: "Fairy Tail", titleJa: "FAIRY TAIL", image: "covers/6702.png", popularity: 367432, isSequel: false, score: 7.2 },
    { titleZh: "化物語", titleEn: "Bakemonogatari", titleJa: "化物語", image: "covers/5081.jpg", popularity: 332267, isSequel: true, score: 8.2 },
    { titleZh: "K-ON！輕音部", titleEn: "K-ON!", titleJa: "けいおん!", image: "covers/5680.png", popularity: 269879, isSequel: false, score: 7.8 },
    { titleZh: "好想告訴你", titleEn: "Kimi ni Todoke: From Me to You", titleJa: "君に届け", image: "covers/6045.jpg", popularity: 240152, isSequel: false, score: 7.9 },
    { titleZh: "科學超電磁砲", titleEn: "A Certain Scientific Railgun", titleJa: "とある科学の超電磁砲", image: "covers/6213.jpg", popularity: 150842, isSequel: false, score: 7.5 },
    { titleZh: "涼宮春日的憂鬱（2009）", titleEn: "The Melancholy of Haruhi Suzumiya (2009)", titleJa: "涼宮ハルヒの憂鬱", image: "covers/4382.png", popularity: 116933, isSequel: false, score: 7.1 },
    { titleZh: "東之伊甸", titleEn: "Eden of the East", titleJa: "東のエデン", image: "covers/5630.png", popularity: 109044, isSequel: false, score: 7.4 },
    { titleZh: "狼與辛香料II", titleEn: "Spice and Wolf II", titleJa: "狼と香辛料II", image: "covers/5341.jpg", popularity: 95683, isSequel: false, score: 8.1 },
    { titleZh: "七龍珠改", titleEn: "Dragon Ball Z Kai", titleJa: "ドラゴンボール改", image: "covers/6033.png", popularity: 94544, isSequel: true, score: 7.7 },
    { titleZh: "天降之物", titleEn: "Heaven's Lost Property", titleJa: "そらのおとしもの", image: "covers/5958.jpg", popularity: 91770, isSequel: false, score: 6.7 },
    { titleZh: "潘朵拉之心", titleEn: "PandoraHearts", titleJa: "パンドラハーツ", image: "covers/5530.jpg", popularity: 73334, isSequel: false, score: 7.2 },
    { titleZh: "東京地震8.0", titleEn: "Tokyo Magnitude 8.0", titleJa: "東京マグニチュード8.0", image: "covers/6211.png", popularity: 69809, isSequel: false, score: 7.7 },
    { titleZh: "DARKER THAN BLACK 流星的雙子", titleEn: "Darker than Black: Gemini of the Meteor", titleJa: "DARKER THAN BLACK -流星の双子-", image: "covers/6573.png", popularity: 62853, isSequel: false, score: 7.1 },
    { titleZh: "幻靈鎮魂曲", titleEn: "Phantom: Requiem for the Phantom", titleJa: "Phantom 〜Requiem for the Phantom〜", image: "covers/5682.png", popularity: 60695, isSequel: false, score: 7.5 },
  ],
  "2010": [
    { titleZh: "Angel Beats!", titleEn: "Angel Beats!", titleJa: "Angel Beats!", image: "covers/6547.png", popularity: 430988, isSequel: false, score: 7.7 },
    { titleZh: "無頭騎士異聞錄 DuRaRaRa!!", titleEn: "Durarara!!", titleJa: "デュラララ!!", image: "covers/6746.png", popularity: 286180, isSequel: false, score: 7.9 },
    { titleZh: "會長是女僕大人！", titleEn: "Maid-Sama!", titleJa: "会長はメイド様!", image: "covers/7054.png", popularity: 279144, isSequel: false, score: 7.8 },
    { titleZh: "學園默示錄 HIGHSCHOOL OF THE DEAD", titleEn: "High School of the Dead", titleJa: "学園黙示録HIGHSCHOOL OF THE DEAD", image: "covers/8074.png", popularity: 277484, isSequel: false, score: 6.7 },
    { titleZh: "K-ON！！輕音部", titleEn: "K-ON! Season 2", titleJa: "けいおん!!", image: "covers/7791.png", popularity: 162887, isSequel: true, score: 8.2 },
    { titleZh: "我的妹妹哪有這麼可愛！", titleEn: "Oreimo", titleJa: "俺の妹がこんなに可愛いわけがない", image: "covers/8769.jpg", popularity: 143275, isSequel: false, score: 6.5 },
    { titleZh: "刀語", titleEn: "Katanagatari", titleJa: "刀語", image: "covers/6594.png", popularity: 131631, isSequel: false, score: 8.1 },
    { titleZh: "只有神知道的世界", titleEn: "The World God Only Knows", titleJa: "神のみぞ知るセカイ", image: "covers/8525.png", popularity: 131406, isSequel: false, score: 7.4 },
    { titleZh: "屍鬼", titleEn: "Shiki", titleJa: "屍鬼", image: "covers/7724.jpg", popularity: 126793, isSequel: false, score: 7.5 },
    { titleZh: "爆漫王。", titleEn: "Bakuman.", titleJa: "バクマン。", image: "covers/7674.png", popularity: 119554, isSequel: false, score: 7.9 },
    { titleZh: "笨蛋、測驗、召喚獸", titleEn: "Baka and Test - Summon the Beasts", titleJa: "バカとテストと召喚獣", image: "covers/6347.jpg", popularity: 116150, isSequel: false, score: 7.1 },
    { titleZh: "妄想學生會", titleEn: "Seitokai Yakuindomo", titleJa: "生徒会役員共", image: "covers/8675.jpg", popularity: 107499, isSequel: false, score: 7.3 },
    { titleZh: "黑執事II", titleEn: "Black Butler II", titleJa: "黒執事II", image: "covers/6707.png", popularity: 100770, isSequel: true, score: 6.7 },
    { titleZh: "魔法禁書目錄II", titleEn: "A Certain Magical Index II", titleJa: "とある魔術の禁書目録II", image: "covers/8937.jpg", popularity: 100660, isSequel: true, score: 7.3 },
    { titleZh: "WORKING!!迷糊餐廳", titleEn: "Wagnaria!!", titleJa: "WORKING!!", image: "covers/6956.jpg", popularity: 90910, isSequel: false, score: 7.4 },
  ],
  "2011": [
    { titleZh: "HUNTER×HUNTER 獵人（2011）", titleEn: "Hunter x Hunter (2011)", titleJa: "HUNTER×HUNTER (2011)", image: "covers/11061.png", popularity: 810226, isSequel: false, score: 8.9 },
    { titleZh: "命運石之門", titleEn: "Steins;Gate", titleJa: "シュタインズ・ゲート", image: "covers/9253.jpg", popularity: 573911, isSequel: false, score: 8.9 },
    { titleZh: "青之驅魔師", titleEn: "Blue Exorcist", titleJa: "青の祓魔師", image: "covers/9919.jpg", popularity: 449742, isSequel: false, score: 7.2 },
    { titleZh: "未來日記", titleEn: "The Future Diary", titleJa: "未来日記", image: "covers/10620.png", popularity: 418528, isSequel: false, score: 6.9 },
    { titleZh: "我們仍未知道那天所看見的花的名字。", titleEn: "Anohana: The Flower We Saw That Day", titleJa: "あの日見た花の名前を僕達はまだ知らない。", image: "covers/9989.jpg", popularity: 384891, isSequel: false, score: 8 },
    { titleZh: "Fate/Zero", titleEn: "Fate/Zero", titleJa: "Fate/Zero", image: "covers/10087.png", popularity: 339087, isSequel: false, score: 8.1 },
    { titleZh: "魔法少女小圓", titleEn: "Puella Magi Madoka Magica", titleJa: "魔法少女まどか☆マギカ", image: "covers/9756.jpg", popularity: 314980, isSequel: false, score: 8.3 },
    { titleZh: "死囚樂園", titleEn: "Deadman Wonderland", titleJa: "デッドマン・ワンダーランド", image: "covers/6880.png", popularity: 243391, isSequel: false, score: 6.7 },
    { titleZh: "罪惡王冠", titleEn: "Guilty Crown", titleJa: "ギルティクラウン", image: "covers/10793.jpg", popularity: 234966, isSequel: false, score: 6.9 },
    { titleZh: "日常", titleEn: "Nichijou - My Ordinary Life", titleJa: "日常", image: "covers/10165.png", popularity: 234161, isSequel: false, score: 8.3 },
    { titleZh: "我的朋友很少", titleEn: "Haganai", titleJa: "僕は友達が少ない", image: "covers/10719.png", popularity: 161690, isSequel: false, score: 6.8 },
    { titleZh: "IS〈Infinite Stratos〉", titleEn: "Infinite Stratos", titleJa: "IS〈インフィニット・ストラトス〉", image: "covers/9041.jpg", popularity: 129085, isSequel: false, score: 6.1 },
    { titleZh: "GOSICK", titleEn: "Gosick", titleJa: "GOSICK", image: "covers/8425.jpg", popularity: 120976, isSequel: false, score: 7.7 },
    { titleZh: "花牌情緣", titleEn: "Chihayafuru", titleJa: "ちはやふる", image: "covers/10800.png", popularity: 120480, isSequel: false, score: 8 },
    { titleZh: "好想告訴你 2ND SEASON", titleEn: "Kimi ni Todoke: From Me to You Season 2", titleJa: "君に届け 2ND SEASON", image: "covers/9656.jpg", popularity: 116286, isSequel: true, score: 7.9 },
  ],
  "2012": [
    { titleZh: "Sword Art Online 刀劍神域", titleEn: "Sword Art Online", titleJa: "ソードアート・オンライン", image: "covers/11757.jpg", popularity: 694355, isSequel: false, score: 7 },
    { titleZh: "JoJo的奇妙冒險（TV）", titleEn: "JoJo's Bizarre Adventure (TV)", titleJa: "ジョジョの奇妙な冒険 (TV)", image: "covers/14719.jpg", popularity: 461386, isSequel: false, score: 7.7 },
    { titleZh: "Another 替身", titleEn: "Another", titleJa: "アナザー", image: "covers/11111.png", popularity: 373633, isSequel: false, score: 7.1 },
    { titleZh: "PSYCHO-PASS 心靈判官", titleEn: "PSYCHO-PASS", titleJa: "PSYCHO-PASS サイコパス", image: "covers/13601.jpg", popularity: 346576, isSequel: false, score: 8.1 },
    { titleZh: "冰菓", titleEn: "Hyouka", titleJa: "氷菓", image: "covers/12189.jpg", popularity: 342046, isSequel: false, score: 7.9 },
    { titleZh: "中二病也想談戀愛！", titleEn: "Love, Chunibyo & Other Delusions", titleJa: "中二病でも恋がしたい!", image: "covers/14741.jpg", popularity: 340568, isSequel: false, score: 7.6 },
    { titleZh: "惡魔高校D×D", titleEn: "High School DxD", titleJa: "ハイスクールD×D", image: "covers/11617.jpg", popularity: 302417, isSequel: false, score: 6.9 },
    { titleZh: "影子籃球員", titleEn: "Kuroko's Basketball", titleJa: "黒子のバスケ", image: "covers/11771.jpg", popularity: 276515, isSequel: false, score: 7.8 },
    { titleZh: "櫻花莊的寵物女孩", titleEn: "The Pet Girl of Sakurasou", titleJa: "さくら荘のペットな彼女", image: "covers/13759.jpg", popularity: 268968, isSequel: false, score: 7.8 },
    { titleZh: "鄰家的怪同學", titleEn: "My Little Monster", titleJa: "となりの怪物くん", image: "covers/14227.jpg", popularity: 252978, isSequel: false, score: 7.2 },
    { titleZh: "Fate/Zero 第二季", titleEn: "Fate/Zero Season 2", titleJa: "Fate/Zero 2ndシーズン", image: "covers/11741.jpg", popularity: 237040, isSequel: true, score: 8.4 },
    { titleZh: "魔奇少年 MAGI", titleEn: "Magi: The Labyrinth of Magic", titleJa: "マギ The labyrinth of magic", image: "covers/14513.jpg", popularity: 226164, isSequel: true, score: 7.8 },
    { titleZh: "男子高中生的日常", titleEn: "Daily Lives of High School Boys", titleJa: "男子高校生の日常", image: "covers/11843.jpg", popularity: 188390, isSequel: false, score: 8 },
    { titleZh: "Kokoro Connect 心靈連結", titleEn: "Kokoro Connect", titleJa: "ココロコネクト", image: "covers/11887.jpg", popularity: 186296, isSequel: false, score: 7.5 },
    { titleZh: "偽物語", titleEn: "Nisemonogatari", titleJa: "偽物語", image: "covers/11597.jpg", popularity: 182379, isSequel: true, score: 7.9 },
  ],
  "2013": [
    { titleZh: "進擊的巨人", titleEn: "Attack on Titan", titleJa: "進撃の巨人", image: "covers/16498.jpg", popularity: 1013208, isSequel: false, score: 8.5 },
    { titleZh: "KILL la KILL", titleEn: "Kill la Kill", titleJa: "キルラキル", image: "covers/18679.png", popularity: 403706, isSequel: false, score: 7.9 },
    { titleZh: "打工吧！魔王大人", titleEn: "The Devil is a Part-Timer!", titleJa: "はたらく魔王さま!", image: "covers/15809.jpg", popularity: 385485, isSequel: false, score: 7.5 },
    { titleZh: "果然我的青春戀愛喜劇搞錯了。", titleEn: "My Teen Romantic Comedy SNAFU", titleJa: "やはり俺の青春ラブコメはまちがっている。", image: "covers/14813.jpg", popularity: 366515, isSequel: false, score: 7.8 },
    { titleZh: "境界的彼方", titleEn: "Beyond the Boundary", titleJa: "境界の彼方", image: "covers/18153.png", popularity: 273430, isSequel: false, score: 7.4 },
    { titleZh: "Golden Time", titleEn: "Golden Time", titleJa: "ゴールデンタイム", image: "covers/17895.jpg", popularity: 255748, isSequel: false, score: 7.5 },
    { titleZh: "約會大作戰 DATE A LIVE", titleEn: "Date A Live", titleJa: "デート・ア・ライブ", image: "covers/15583.jpg", popularity: 238455, isSequel: false, score: 6.8 },
    { titleZh: "記錄的地平線", titleEn: "Log Horizon", titleJa: "ログ・ホライズン", image: "covers/17265.jpg", popularity: 231095, isSequel: false, score: 7.6 },
    { titleZh: "槍彈辯駁 希望的學園與絕望的高中生 The Animation", titleEn: "Danganronpa: The Animation", titleJa: "ダンガンロンパ 希望の学園と絶望の高校生 The Animation", image: "covers/16592.jpg", popularity: 227390, isSequel: true, score: 6.9 },
    { titleZh: "惡魔高校D×D NEW", titleEn: "High School DxD NEW", titleJa: "ハイスクールD×D NEW", image: "covers/15451.jpg", popularity: 190995, isSequel: true, score: 7.1 },
    { titleZh: "Free！男子游泳部", titleEn: "Free! -Iwatobi Swim Club-", titleJa: "Free!", image: "covers/18507.png", popularity: 179816, isSequel: false, score: 7.2 },
    { titleZh: "影子籃球員 第二季", titleEn: "Kuroko's Basketball 2", titleJa: "黒子のバスケ 2nd SEASON", image: "covers/16894.jpg", popularity: 177325, isSequel: true, score: 8 },
    { titleZh: "物語系列 第二季", titleEn: "Monogatari Series Second Season", titleJa: "〈物語〉シリーズ セカンドシーズン", image: "covers/17074.png", popularity: 167982, isSequel: true, score: 8.8 },
    { titleZh: "魔奇少年 MAGI 王國", titleEn: "Magi: The Kingdom of Magic", titleJa: "マギ The kingdom of magic", image: "covers/18115.png", popularity: 164705, isSequel: true, score: 8.1 },
    { titleZh: "我不受歡迎，怎麼想都是你們的錯！", titleEn: "WataMote: No Matter How I Look At It, It's You Guys' Fault I'm Not Popular!", titleJa: "私がモテないのはどう考えてもお前らが悪い!", image: "covers/16742.jpg", popularity: 149320, isSequel: false, score: 6.7 },
  ],
  "2014": [
    { titleZh: "東京喰種", titleEn: "Tokyo Ghoul", titleJa: "東京喰種 トーキョーグール", image: "covers/20605.jpg", popularity: 714397, isSequel: false, score: 7.6 },
    { titleZh: "四月是你的謊言", titleEn: "Your lie in April", titleJa: "四月は君の嘘", image: "covers/20665.png", popularity: 592264, isSequel: false, score: 8.4 },
    { titleZh: "排球少年!!", titleEn: "HAIKYU!!", titleJa: "ハイキュー!!", image: "covers/20464.png", popularity: 565268, isSequel: false, score: 8.4 },
    { titleZh: "NO GAME NO LIFE 遊戲人生", titleEn: "No Game, No Life", titleJa: "ノーゲーム・ノーライフ", image: "covers/19815.jpg", popularity: 526786, isSequel: false, score: 7.7 },
    { titleZh: "流浪神差", titleEn: "Noragami", titleJa: "ノラガミ", image: "covers/20447.jpg", popularity: 525017, isSequel: false, score: 7.8 },
    { titleZh: "斬！赤紅之瞳", titleEn: "Akame ga Kill!", titleJa: "アカメが斬る！", image: "covers/20613.jpg", popularity: 521577, isSequel: false, score: 7.3 },
    { titleZh: "七大罪", titleEn: "The Seven Deadly Sins", titleJa: "七つの大罪", image: "covers/20789.jpg", popularity: 513186, isSequel: false, score: 7.3 },
    { titleZh: "寄生獸 生命的準則", titleEn: "Parasyte -the maxim-", titleJa: "寄生獣 セイの格率", image: "covers/20623.jpg", popularity: 485428, isSequel: false, score: 8.1 },
    { titleZh: "Sword Art Online 刀劍神域 II", titleEn: "Sword Art Online II", titleJa: "ソードアート・オンライン II", image: "covers/20594.jpg", popularity: 438593, isSequel: true, score: 6.6 },
    { titleZh: "JoJo的奇妙冒險 星塵鬥士", titleEn: "JoJo's Bizarre Adventure: Stardust Crusaders", titleJa: "ジョジョの奇妙な冒険 スターダストクルセイダース", image: "covers/20474.jpg", popularity: 332975, isSequel: true, score: 7.9 },
    { titleZh: "殘響的恐怖", titleEn: "Terror in Resonance", titleJa: "残響のテロル", image: "covers/20661.png", popularity: 280318, isSequel: false, score: 7.8 },
    { titleZh: "偽戀", titleEn: "Nisekoi", titleJa: "ニセコイ", image: "covers/18897.jpg", popularity: 260292, isSequel: false, score: 7.3 },
    { titleZh: "Fate/stay night [Unlimited Blade Works]", titleEn: "Fate/stay night: Unlimited Blade Works", titleJa: "Fate/stay night [Unlimited Blade Works]", image: "covers/19603.jpg", popularity: 257670, isSequel: true, score: 8 },
    { titleZh: "魔法科高中的劣等生", titleEn: "The Irregular at Magic High School", titleJa: "魔法科高校の劣等生", image: "covers/20458.jpg", popularity: 251646, isSequel: false, score: 7 },
    { titleZh: "青春之旅", titleEn: "Blue Spring Ride", titleJa: "アオハライド", image: "covers/20596.png", popularity: 237061, isSequel: false, score: 7.5 },
  ],
  "2015": [
    { titleZh: "ONE PUNCH MAN 一拳超人", titleEn: "One-Punch Man", titleJa: "ワンパンマン", image: "covers/21087.jpg", popularity: 744220, isSequel: false, score: 8.3 },
    { titleZh: "暗殺教室", titleEn: "Assassination Classroom", titleJa: "暗殺教室", image: "covers/20755.jpg", popularity: 608169, isSequel: false, score: 7.9 },
    { titleZh: "死亡遊行", titleEn: "Death Parade", titleJa: "デス・パレード", image: "covers/20931.jpg", popularity: 454703, isSequel: false, score: 8 },
    { titleZh: "Charlotte", titleEn: "Charlotte", titleJa: "Charlotte(シャーロット)", image: "covers/20997.jpg", popularity: 418186, isSequel: false, score: 7.5 },
    { titleZh: "東京喰種√A", titleEn: "Tokyo Ghoul √A", titleJa: "東京喰種[トーキョーグール]√A", image: "covers/20850.jpg", popularity: 394589, isSequel: true, score: 6.7 },
    { titleZh: "食戟之靈", titleEn: "Food Wars!", titleJa: "食戟のソーマ", image: "covers/20923.jpg", popularity: 392689, isSequel: false, score: 7.8 },
    { titleZh: "OVERLORD", titleEn: "Overlord", titleJa: "オーバーロード", image: "covers/20832.jpg", popularity: 389084, isSequel: false, score: 7.7 },
    { titleZh: "排球少年!! 第二季", titleEn: "HAIKYU!! 2nd Season", titleJa: "ハイキュー!! セカンドシーズン", image: "covers/20992.png", popularity: 387878, isSequel: true, score: 8.6 },
    { titleZh: "在地下城尋求邂逅是否搞錯了什麼", titleEn: "Is It Wrong to Try to Pick Up Girls in a Dungeon?", titleJa: "ダンジョンに出会いを求めるのは間違っているだろうか", image: "covers/20920.jpg", popularity: 383734, isSequel: false, score: 7.3 },
    { titleZh: "終結的熾天使", titleEn: "Seraph of the End: Vampire Reign", titleJa: "終わりのセラフ", image: "covers/20829.png", popularity: 317781, isSequel: false, score: 7.3 },
    { titleZh: "流浪神差 ARAGOTO", titleEn: "Noragami Aragoto", titleJa: "ノラガミ ARAGOTO", image: "covers/21128.jpg", popularity: 304143, isSequel: true, score: 8 },
    { titleZh: "JoJo的奇妙冒險 星塵鬥士 埃及篇", titleEn: "JoJo's Bizarre Adventure: Stardust Crusaders - Battle in Egypt", titleJa: "ジョジョの奇妙な冒険 スターダストクルセイダース エジプト編", image: "covers/20799.jpg", popularity: 281486, isSequel: true, score: 8.2 },
    { titleZh: "果然我的青春戀愛喜劇搞錯了。續", titleEn: "My Teen Romantic Comedy SNAFU TOO!", titleJa: "やはり俺の青春ラブコメはまちがっている。続", image: "covers/20698.png", popularity: 266822, isSequel: true, score: 8.1 },
    { titleZh: "可塑性記憶", titleEn: "Plastic Memories", titleJa: "プラスティックメモリーズ", image: "covers/20872.jpg", popularity: 250451, isSequel: false, score: 7.7 },
    { titleZh: "監獄學園", titleEn: "Prison School", titleJa: "監獄学園〈プリズンスクール〉", image: "covers/20807.jpg", popularity: 239309, isSequel: false, score: 7.3 },
  ],
  "2016": [
    { titleZh: "我的英雄學院", titleEn: "My Hero Academia", titleJa: "僕のヒーローアカデミア", image: "covers/21459.jpg", popularity: 844624, isSequel: false, score: 7.7 },
    { titleZh: "路人超能100", titleEn: "Mob Psycho 100", titleJa: "モブサイコ100", image: "covers/21507.jpg", popularity: 603294, isSequel: false, score: 8.4 },
    { titleZh: "Re:從零開始的異世界生活", titleEn: "Re:ZERO -Starting Life in Another World-", titleJa: "Re:ゼロから始める異世界生活", image: "covers/21355.jpg", popularity: 593298, isSequel: false, score: 8.1 },
    { titleZh: "只有我不存在的城市", titleEn: "ERASED", titleJa: "僕だけがいない街", image: "covers/21234.jpg", popularity: 586250, isSequel: false, score: 8.1 },
    { titleZh: "為美好的世界獻上祝福！", titleEn: "KONOSUBA -God's blessing on this wonderful world!", titleJa: "この素晴らしい世界に祝福を！", image: "covers/21202.png", popularity: 499401, isSequel: false, score: 7.9 },
    { titleZh: "文豪Stray Dogs", titleEn: "Bungo Stray Dogs", titleJa: "文豪ストレイドッグス", image: "covers/21311.jpg", popularity: 408113, isSequel: false, score: 7.7 },
    { titleZh: "暗殺教室 第二季", titleEn: "Assassination Classroom Second Season", titleJa: "暗殺教室 第２期", image: "covers/21170.jpg", popularity: 358503, isSequel: true, score: 8.3 },
    { titleZh: "排球少年!! 烏野高中 VS 白鳥澤學園高中", titleEn: "HAIKYU!! 3rd Season", titleJa: "ハイキュー!! 烏野高校 VS 白鳥沢学園高校", image: "covers/21698.png", popularity: 352566, isSequel: true, score: 8.7 },
    { titleZh: "JoJo的奇妙冒險 不滅鑽石", titleEn: "JoJo's Bizarre Adventure: Diamond is Unbreakable", titleJa: "ジョジョの奇妙な冒険 ダイヤモンドは砕けない", image: "covers/21450.jpg", popularity: 304618, isSequel: true, score: 8.4 },
    { titleZh: "食戟之靈 貳之皿", titleEn: "Food Wars! The Second Plate", titleJa: "食戟のソーマ 弍ノ皿", image: "covers/21518.jpg", popularity: 254529, isSequel: true, score: 7.9 },
    { titleZh: "ReLIFE 重返17歲", titleEn: "ReLIFE", titleJa: "ReLIFE", image: "covers/21049.png", popularity: 250317, isSequel: false, score: 7.8 },
    { titleZh: "orange", titleEn: "Orange", titleJa: "orange", image: "covers/21647.png", popularity: 228925, isSequel: false, score: 7.5 },
    { titleZh: "Yuri!!! on ICE", titleEn: "Yuri!!! on ICE", titleJa: "ユーリ!!! on ICE", image: "covers/21709.png", popularity: 226126, isSequel: false, score: 7.8 },
    { titleZh: "3月的獅子", titleEn: "March comes in like a lion", titleJa: "３月のライオン", image: "covers/21366.jpg", popularity: 208499, isSequel: false, score: 8.3 },
    { titleZh: "羈絆者 KIZNAIVER", titleEn: "Kiznaiver", titleJa: "キズナイーバー", image: "covers/21421.jpg", popularity: 197259, isSequel: false, score: 7.2 },
  ],
  "2017": [
    { titleZh: "進擊的巨人 第二季", titleEn: "Attack on Titan Season 2", titleJa: "進撃の巨人 Season２", image: "covers/20958.jpg", popularity: 708554, isSequel: true, score: 8.5 },
    { titleZh: "我的英雄學院 第二季", titleEn: "My Hero Academia Season 2", titleJa: "僕のヒーローアカデミア２", image: "covers/21856.png", popularity: 636454, isSequel: true, score: 8 },
    { titleZh: "黑色五葉草", titleEn: "Black Clover", titleJa: "ブラッククローバー", image: "covers/97940.png", popularity: 557446, isSequel: false, score: 7.9 },
    { titleZh: "狂賭之淵", titleEn: "Kakegurui", titleJa: "賭ケグルイ", image: "covers/98314.jpg", popularity: 443971, isSequel: false, score: 7 },
    { titleZh: "歡迎來到實力至上主義的教室", titleEn: "Classroom of the Elite", titleJa: "ようこそ実力至上主義の教室へ", image: "covers/98659.jpg", popularity: 427925, isSequel: false, score: 7.6 },
    { titleZh: "來自深淵", titleEn: "Made in Abyss", titleJa: "メイドインアビス", image: "covers/97986.jpg", popularity: 392098, isSequel: false, score: 8.5 },
    { titleZh: "為美好的世界獻上祝福！2", titleEn: "KONOSUBA -God's blessing on this wonderful world! 2", titleJa: "この素晴らしい世界に祝福を！2", image: "covers/21699.png", popularity: 364334, isSequel: true, score: 8.1 },
    { titleZh: "小林家的龍女僕", titleEn: "Miss Kobayashi's Dragon Maid", titleJa: "小林さんちのメイドラゴン", image: "covers/21776.png", popularity: 321307, isSequel: false, score: 7.7 },
    { titleZh: "幼女戰記", titleEn: "Saga of Tanya the Evil", titleJa: "幼女戦記", image: "covers/21613.png", popularity: 259752, isSequel: false, score: 7.8 },
    { titleZh: "魔法使的新娘", titleEn: "The Ancient Magus' Bride", titleJa: "魔法使いの嫁", image: "covers/98436.png", popularity: 238648, isSequel: false, score: 7.8 },
    { titleZh: "政宗君的復仇", titleEn: "Masamune-kun's Revenge", titleJa: "政宗くんのリベンジ", image: "covers/21857.jpg", popularity: 234314, isSequel: false, score: 6.6 },
    { titleZh: "食戟之靈 餐之皿", titleEn: "Food Wars! The Third Plate", titleJa: "食戟のソーマ 餐ノ皿", image: "covers/99255.jpg", popularity: 222662, isSequel: true, score: 7.8 },
    { titleZh: "BORUTO-火影新世代-", titleEn: "Boruto: Naruto Next Generations", titleJa: "BORUTO-ボルト- NARUTO NEXT GENERATIONS", image: "covers/97938.jpg", popularity: 219310, isSequel: true, score: 5.7 },
    { titleZh: "不正經的魔術講師與禁忌教典", titleEn: "Akashic Records of Bastard Magic Instructor", titleJa: "ロクでなし魔術講師と禁忌教典(アカシックレコード)", image: "covers/21700.jpg", popularity: 192674, isSequel: false, score: 6.8 },
    { titleZh: "情色漫畫老師", titleEn: "Eromanga Sensei", titleJa: "エロマンガ先生", image: "covers/21685.jpg", popularity: 182215, isSequel: false, score: 6 },
  ],
  "2018": [
    { titleZh: "進擊的巨人 第三季", titleEn: "Attack on Titan Season 3", titleJa: "進撃の巨人 Season３", image: "covers/99147.jpg", popularity: 662490, isSequel: true, score: 8.6 },
    { titleZh: "我的英雄學院 第三季", titleEn: "My Hero Academia Season 3", titleJa: "僕のヒーローアカデミア３", image: "covers/100166.jpg", popularity: 583320, isSequel: true, score: 7.9 },
    { titleZh: "青春豬頭少年不會夢到兔女郎學姊", titleEn: "Rascal Does Not Dream of Bunny Girl Senpai", titleJa: "青春ブタ野郎はバニーガール先輩の夢を見ない", image: "covers/101291.jpg", popularity: 556959, isSequel: false, score: 8.1 },
    { titleZh: "紫羅蘭永恆花園", titleEn: "Violet Evergarden", titleJa: "ヴァイオレット・エヴァーガーデン", image: "covers/21827.png", popularity: 528731, isSequel: false, score: 8.5 },
    { titleZh: "DARLING in the FRANXX", titleEn: "DARLING in the FRANXX", titleJa: "ダーリン・イン・ザ・フランキス", image: "covers/99423.png", popularity: 482118, isSequel: false, score: 7 },
    { titleZh: "關於我轉生變成史萊姆這檔事", titleEn: "That Time I Got Reincarnated as a Slime", titleJa: "転生したらスライムだった件", image: "covers/101280.jpg", popularity: 439894, isSequel: false, score: 8 },
    { titleZh: "惡魔人 crybaby", titleEn: "Devilman Crybaby", titleJa: "DEVILMAN crybaby", image: "covers/98460.png", popularity: 341665, isSequel: false, score: 7.6 },
    { titleZh: "阿宅的戀愛太難", titleEn: "Wotakoi: Love is Hard for Otaku", titleJa: "ヲタクに恋は難しい", image: "covers/99578.png", popularity: 316854, isSequel: false, score: 7.8 },
    { titleZh: "BANANA FISH", titleEn: "BANANA FISH", titleJa: "BANANA FISH", image: "covers/100388.jpg", popularity: 300732, isSequel: false, score: 8.4 },
    { titleZh: "東京喰種:re", titleEn: "Tokyo Ghoul:re", titleJa: "東京喰種-トーキョーグール-:re", image: "covers/100240.jpg", popularity: 298439, isSequel: true, score: 6.2 },
    { titleZh: "哥布林殺手", titleEn: "GOBLIN SLAYER", titleJa: "ゴブリンスレイヤー", image: "covers/101165.jpg", popularity: 293397, isSequel: false, score: 7.1 },
    { titleZh: "JoJo的奇妙冒險 黃金之風", titleEn: "JoJo's Bizarre Adventure: Golden Wind", titleJa: "ジョジョの奇妙な冒険 黄金の風", image: "covers/102883.png", popularity: 289652, isSequel: true, score: 8.5 },
    { titleZh: "Sword Art Online 刀劍神域 Alicization", titleEn: "Sword Art Online: Alicization", titleJa: "ソードアート・オンライン アリシゼーション", image: "covers/100182.jpg", popularity: 280012, isSequel: false, score: 7.5 },
    { titleZh: "七大罪 戒律的復活", titleEn: "The Seven Deadly Sins: Revival of the Commandments", titleJa: "七つの大罪 戒めの復活", image: "covers/99539.jpg", popularity: 278678, isSequel: true, score: 7.3 },
    { titleZh: "OVERLORD II", titleEn: "Overlord II", titleJa: "オーバーロードⅡ", image: "covers/98437.jpg", popularity: 257322, isSequel: true, score: 7.6 },
  ],
  "2019": [
    { titleZh: "鬼滅之刃", titleEn: "Demon Slayer: Kimetsu no Yaiba", titleJa: "鬼滅の刃", image: "covers/101922.jpg", popularity: 957769, isSequel: false, score: 8.3 },
    { titleZh: "約定的夢幻島", titleEn: "The Promised Neverland", titleJa: "約束のネバーランド", image: "covers/101759.jpg", popularity: 615452, isSequel: false, score: 8.4 },
    { titleZh: "進擊的巨人 第三季 Part.2", titleEn: "Attack on Titan Season 3 Part 2", titleJa: "進撃の巨人 Season３ Part.2", image: "covers/104578.jpg", popularity: 589909, isSequel: true, score: 9 },
    { titleZh: "輝夜姬想讓人告白～天才們的戀愛頭腦戰～", titleEn: "Kaguya-sama: Love is War", titleJa: "かぐや様は告らせたい～天才たちの恋愛頭脳戦～", image: "covers/101921.jpg", popularity: 538281, isSequel: false, score: 8.3 },
    { titleZh: "Dr.STONE 新石紀", titleEn: "Dr. STONE", titleJa: "Dr.STONE", image: "covers/105333.jpg", popularity: 534364, isSequel: false, score: 8.1 },
    { titleZh: "海盜戰記 VINLAND SAGA", titleEn: "Vinland Saga", titleJa: "ヴィンランド・サガ", image: "covers/101348.jpg", popularity: 520149, isSequel: false, score: 8.7 },
    { titleZh: "我的英雄學院 第四季", titleEn: "My Hero Academia Season 4", titleJa: "僕のヒーローアカデミア４", image: "covers/104276.png", popularity: 516183, isSequel: true, score: 7.9 },
    { titleZh: "炎炎消防隊", titleEn: "Fire Force", titleJa: "炎炎ノ消防隊", image: "covers/105310.jpg", popularity: 465839, isSequel: false, score: 7.6 },
    { titleZh: "一拳超人 第二季", titleEn: "One-Punch Man Season 2", titleJa: "ワンパンマン 2", image: "covers/97668.png", popularity: 453473, isSequel: true, score: 7.4 },
    { titleZh: "盾之勇者成名錄", titleEn: "The Rising of the Shield Hero", titleJa: "盾の勇者の成り上がり", image: "covers/99263.jpg", popularity: 444318, isSequel: false, score: 7.7 },
    { titleZh: "路人超能100 II", titleEn: "Mob Psycho 100 II", titleJa: "モブサイコ100 II", image: "covers/101338.jpg", popularity: 434884, isSequel: true, score: 8.7 },
    { titleZh: "多羅羅", titleEn: "Dororo", titleJa: "どろろ", image: "covers/101347.jpg", popularity: 362145, isSequel: false, score: 8.1 },
    { titleZh: "五等分的新娘", titleEn: "The Quintessential Quintuplets", titleJa: "五等分の花嫁", image: "covers/103572.png", popularity: 305297, isSequel: false, score: 7.6 },
    { titleZh: "Fruits Basket 幻影天使", titleEn: "Fruits Basket (2019)", titleJa: "フルーツバスケット 1st Season", image: "covers/105334.jpg", popularity: 300986, isSequel: false, score: 8.2 },
    { titleZh: "BEASTARS", titleEn: "BEASTARS", titleJa: "BEASTARS", image: "covers/107660.png", popularity: 252158, isSequel: false, score: 7.7 },
  ],
  "2020": [
    { titleZh: "咒術迴戰", titleEn: "JUJUTSU KAISEN", titleJa: "呪術廻戦", image: "covers/113415.jpg", popularity: 929098, isSequel: false, score: 8.4 },
    { titleZh: "輝夜姬想讓人告白？～天才們的戀愛頭腦戰～", titleEn: "Kaguya-sama: Love is War?", titleJa: "かぐや様は告らせたい？～天才たちの恋愛頭脳戦～", image: "covers/112641.jpg", popularity: 421093, isSequel: true, score: 8.5 },
    { titleZh: "Re:從零開始的異世界生活 第二季", titleEn: "Re:ZERO -Starting Life in Another World- Season 2", titleJa: "Re:ゼロから始める異世界生活 2nd Season", image: "covers/108632.jpg", popularity: 361376, isSequel: true, score: 8.3 },
    { titleZh: "神之塔 Tower of God", titleEn: "Tower of God", titleJa: "神之塔 -Tower of God-", image: "covers/115230.jpg", popularity: 325691, isSequel: false, score: 7.4 },
    { titleZh: "租借女友", titleEn: "Rent-a-Girlfriend", titleJa: "彼女、お借りします", image: "covers/113813.jpg", popularity: 299784, isSequel: false, score: 6.6 },
    { titleZh: "炎炎消防隊 貳之章", titleEn: "Fire Force Season 2", titleJa: "炎炎ノ消防隊 弐ノ章", image: "covers/114236.png", popularity: 290832, isSequel: true, score: 7.8 },
    { titleZh: "高校之神", titleEn: "The God of High School", titleJa: "THE GOD OF HIGH SCHOOL ゴッド・オブ・ハイスクール", image: "covers/116006.png", popularity: 290576, isSequel: false, score: 7 },
    { titleZh: "排球少年!! TO THE TOP", titleEn: "HAIKYU!! TO THE TOP", titleJa: "ハイキュー!! TO THE TOP", image: "covers/106625.png", popularity: 285914, isSequel: false, score: 8.3 },
    { titleZh: "魔王學院的不適任者～史上最強的魔王始祖、轉生就讀子孫們的學校～", titleEn: "The Misfit of Demon King Academy: History’s Strongest Demon King Reincarnates and Goes to School with His Descendants", titleJa: "魔王学院の不適合者 ～史上最強の魔王の始祖、転生して子孫たちの学校へ通う～", image: "covers/112301.jpg", popularity: 256647, isSequel: false, score: 7.2 },
    { titleZh: "總之就是非常可愛", titleEn: "TONIKAWA: Over The Moon For You", titleJa: "トニカクカワイイ", image: "covers/116267.jpg", popularity: 236470, isSequel: false, score: 7.7 },
    { titleZh: "地縛少年花子君", titleEn: "Toilet-bound Hanako-kun", titleJa: "地縛少年 花子くん", image: "covers/108463.jpg", popularity: 232007, isSequel: false, score: 7.8 },
    { titleZh: "大欺詐師 GREAT PRETENDER", titleEn: "Great Pretender", titleJa: "GREAT PRETENDER", image: "covers/110349.png", popularity: 224431, isSequel: false, score: 8.1 },
    { titleZh: "果然我的青春戀愛喜劇搞錯了。完", titleEn: "My Teen Romantic Comedy SNAFU Climax!", titleJa: "やはり俺の青春ラブコメはまちがっている。完", image: "covers/108489.png", popularity: 216068, isSequel: true, score: 8.2 },
    { titleZh: "在地下城尋求邂逅是否搞錯了什麼 III", titleEn: "Is It Wrong to Try to Pick Up Girls in a Dungeon? III", titleJa: "ダンジョンに出会いを求めるのは間違っているだろうかⅢ", image: "covers/112124.jpg", popularity: 192690, isSequel: true, score: 7.4 },
    { titleZh: "Sword Art Online 刀劍神域 Alicization War of Underworld 最終章", titleEn: "Sword Art Online: Alicization - War of Underworld Part 2", titleJa: "ソードアート・オンライン アリシゼーション War of Underworld 最終章 (2nd Season)", image: "covers/114308.jpg", popularity: 190528, isSequel: true, score: 7.4 },
  ],
  "2021": [
    { titleZh: "進擊的巨人 最終季", titleEn: "Attack on Titan Final Season", titleJa: "進撃の巨人 The Final Season", image: "covers/110277.jpg", popularity: 619588, isSequel: true, score: 8.7 },
    { titleZh: "堀與宮村", titleEn: "Horimiya", titleJa: "ホリミヤ", image: "covers/124080.jpg", popularity: 513749, isSequel: false, score: 8.1 },
    { titleZh: "東京復仇者", titleEn: "Tokyo Revengers", titleJa: "東京リベンジャーズ", image: "covers/120120.jpg", popularity: 431703, isSequel: false, score: 7.7 },
    { titleZh: "無職轉生～到了異世界就拿出真本事～", titleEn: "Mushoku Tensei: Jobless Reincarnation", titleJa: "無職転生 ～異世界行ったら本気だす～", image: "covers/108465.jpg", popularity: 429470, isSequel: false, score: 8.2 },
    { titleZh: "我的英雄學院 第五季", titleEn: "My Hero Academia Season 5", titleJa: "僕のヒーローアカデミア５", image: "covers/117193.jpg", popularity: 400196, isSequel: true, score: 7.3 },
    { titleZh: "鬼滅之刃 無限列車篇", titleEn: "Demon Slayer: Kimetsu no Yaiba Mugen Train Arc", titleJa: "鬼滅の刃 無限列車編 (TV)", image: "covers/129874.jpg", popularity: 345062, isSequel: true, score: 8.2 },
    { titleZh: "Dr.STONE 新石紀 STONE WARS", titleEn: "Dr. STONE: STONE WARS", titleJa: "Dr.STONE STONE WARS", image: "covers/113936.jpg", popularity: 323736, isSequel: true, score: 8.1 },
    { titleZh: "約定的夢幻島 第二季", titleEn: "The Promised Neverland Season 2", titleJa: "約束のネバーランド2", image: "covers/108725.jpg", popularity: 314578, isSequel: true, score: 5.2 },
    { titleZh: "古見同學是溝通魯蛇。", titleEn: "Komi Can’t Communicate", titleJa: "古見さんは、コミュ症です。", image: "covers/133965.png", popularity: 308008, isSequel: false, score: 7.6 },
    { titleZh: "致不滅的你", titleEn: "To Your Eternity", titleJa: "不滅のあなたへ", image: "covers/114535.jpg", popularity: 306775, isSequel: false, score: 8.1 },
    { titleZh: "關於我轉生變成史萊姆這檔事 第二季", titleEn: "That Time I Got Reincarnated as a Slime Season 2", titleJa: "転生したらスライムだった件 第2期", image: "covers/108511.jpg", popularity: 306398, isSequel: false, score: 8.3 },
    { titleZh: "86 -不存在的戰區-", titleEn: "86 EIGHTY-SIX", titleJa: "86－エイティシックス－", image: "covers/116589.jpg", popularity: 306036, isSequel: false, score: 8.3 },
    { titleZh: "Re:從零開始的異世界生活 第二季 後半", titleEn: "Re:ZERO -Starting Life in Another World- Season 2 Part 2", titleJa: "Re:ゼロから始める異世界生活 2nd Season Part 2", image: "covers/119661.png", popularity: 291084, isSequel: true, score: 8.4 },
    { titleZh: "WONDER EGG PRIORITY", titleEn: "WONDER EGG PRIORITY", titleJa: "ワンダーエッグ・プライオリティ", image: "covers/124845.jpg", popularity: 277934, isSequel: false, score: 7.4 },
    { titleZh: "別逗我了，長瀞同學", titleEn: "DON'T TOY WITH ME, MISS NAGATORO", titleJa: "イジらないで、長瀞さん", image: "covers/120697.jpg", popularity: 259026, isSequel: false, score: 6.9 },
  ],
  "2022": [
    { titleZh: "鏈鋸人", titleEn: "Chainsaw Man", titleJa: "チェンソーマン", image: "covers/127230.png", popularity: 597876, isSequel: false, score: 8.3 },
    { titleZh: "SPY×FAMILY 間諜家家酒", titleEn: "SPY x FAMILY", titleJa: "SPY×FAMILY", image: "covers/140960.jpg", popularity: 546030, isSequel: false, score: 8.3 },
    { titleZh: "鬼滅之刃 遊郭篇", titleEn: "Demon Slayer: Kimetsu no Yaiba Entertainment District Arc", titleJa: "鬼滅の刃 遊郭編", image: "covers/142329.jpg", popularity: 463193, isSequel: true, score: 8.6 },
    { titleZh: "進擊的巨人 最終季 Part 2", titleEn: "Attack on Titan Final Season Part 2", titleJa: "進撃の巨人 The Final Season Part 2", image: "covers/131681.jpg", popularity: 421064, isSequel: true, score: 8.6 },
    { titleZh: "戀上換裝娃娃", titleEn: "My Dress-Up Darling", titleJa: "その着せ替え人形は恋をする", image: "covers/132405.jpg", popularity: 403260, isSequel: false, score: 8 },
    { titleZh: "電馭叛客：邊緣行者", titleEn: "Cyberpunk: Edgerunners", titleJa: "サイバーパンク エッジランナーズ", image: "covers/120377.jpg", popularity: 356296, isSequel: false, score: 8.5 },
    { titleZh: "BLUE LOCK 藍色監獄", titleEn: "BLUE LOCK", titleJa: "ブルーロック", image: "covers/137822.png", popularity: 307415, isSequel: false, score: 8 },
    { titleZh: "我想成為影之強者！", titleEn: "The Eminence in Shadow", titleJa: "陰の実力者になりたくて！", image: "covers/130298.jpg", popularity: 294222, isSequel: false, score: 8.1 },
    { titleZh: "輝夜姬想讓人告白 -Ultra Romantic-", titleEn: "Kaguya-sama: Love is War -Ultra Romantic-", titleJa: "かぐや様は告らせたい-ウルトラロマンティック-", image: "covers/125367.png", popularity: 280734, isSequel: true, score: 8.9 },
    { titleZh: "徹夜之歌", titleEn: "Call of the Night", titleJa: "よふかしのうた", image: "covers/141391.jpg", popularity: 265483, isSequel: false, score: 7.9 },
    { titleZh: "我的英雄學院 第六季", titleEn: "My Hero Academia Season 6", titleJa: "僕のヒーローアカデミア６", image: "covers/139630.jpg", popularity: 256318, isSequel: true, score: 8.2 },
    { titleZh: "路人超能100 III", titleEn: "Mob Psycho 100 III", titleJa: "モブサイコ100 Ⅲ", image: "covers/140439.jpg", popularity: 252490, isSequel: true, score: 8.7 },
    { titleZh: "孤獨搖滾！", titleEn: "BOCCHI THE ROCK!", titleJa: "ぼっち・ざ・ろっく！", image: "covers/130003.png", popularity: 251281, isSequel: false, score: 8.7 },
    { titleZh: "歡迎來到實力至上主義的教室 第二季", titleEn: "Classroom of the Elite Season 2", titleJa: "ようこそ実力至上主義の教室へ 2nd Season", image: "covers/145545.png", popularity: 248246, isSequel: true, score: 7.9 },
    { titleZh: "盾之勇者成名錄 第二季", titleEn: "The Rising of the Shield Hero Season 2", titleJa: "盾の勇者の成り上がり Season 2", image: "covers/111321.png", popularity: 236910, isSequel: true, score: 6.5 },
  ],
  "2023": [
    { titleZh: "咒術迴戰 第二季", titleEn: "JUJUTSU KAISEN Season 2", titleJa: "呪術廻戦 第2期", image: "covers/145064.jpg", popularity: 462462, isSequel: true, score: 8.6 },
    { titleZh: "葬送的芙莉蓮", titleEn: "Frieren: Beyond Journey’s End", titleJa: "葬送のフリーレン", image: "covers/154587.jpg", popularity: 444780, isSequel: false, score: 9.1 },
    { titleZh: "鬼滅之刃 刀匠村篇", titleEn: "Demon Slayer: Kimetsu no Yaiba Swordsmith Village Arc", titleJa: "鬼滅の刃 刀鍛冶の里編", image: "covers/145139.png", popularity: 354251, isSequel: true, score: 8.1 },
    { titleZh: "地獄樂", titleEn: "Hell’s Paradise", titleJa: "地獄楽", image: "covers/128893.jpg", popularity: 341107, isSequel: false, score: 8 },
    { titleZh: "【我推的孩子】", titleEn: "Oshi No Ko", titleJa: "【推しの子】", image: "covers/150672.png", popularity: 313601, isSequel: false, score: 8.4 },
    { titleZh: "藥師少女的獨語", titleEn: "The Apothecary Diaries", titleJa: "薬屋のひとりごと", image: "covers/161645.jpg", popularity: 298179, isSequel: false, score: 8.8 },
    { titleZh: "MASHLE 魔法少年", titleEn: "MASHLE: MAGIC AND MUSCLES", titleJa: "マッシュル-MASHLE-", image: "covers/151801.png", popularity: 272699, isSequel: false, score: 7.6 },
    { titleZh: "海盜戰記 VINLAND SAGA 第二季", titleEn: "Vinland Saga Season 2", titleJa: "ヴィンランド・サガ SEASON2", image: "covers/136430.jpg", popularity: 259945, isSequel: true, score: 8.8 },
    { titleZh: "無職轉生 II ～到了異世界就拿出真本事～", titleEn: "Mushoku Tensei: Jobless Reincarnation Season 2", titleJa: "無職転生Ⅱ ～異世界行ったら本気だす～", image: "covers/146065.png", popularity: 241775, isSequel: true, score: 8.1 },
    { titleZh: "殭屍100～在成為殭屍前要做的100件事～", titleEn: "Zom 100: Bucket List of the Dead", titleJa: "ゾン100～ゾンビになるまでにしたい100のこと～", image: "covers/159831.png", popularity: 229109, isSequel: false, score: 7.6 },
    { titleZh: "SPY×FAMILY 間諜家家酒 第二季", titleEn: "SPY x FAMILY Season 2", titleJa: "SPY×FAMILY Season 2", image: "covers/158927.png", popularity: 225870, isSequel: true, score: 8 },
    { titleZh: "天國大魔境", titleEn: "Tengoku Daimakyo", titleJa: "天国大魔境", image: "covers/155783.jpg", popularity: 203382, isSequel: false, score: 8.1 },
    { titleZh: "Dr.STONE 新石紀 NEW WORLD", titleEn: "Dr. STONE New World", titleJa: "Dr.STONE NEW WORLD", image: "covers/131518.jpg", popularity: 192326, isSequel: false, score: 8.1 },
    { titleZh: "和山田談場Lv999的戀愛", titleEn: "My Love Story with Yamada-kun at Lv999", titleJa: "山田くんとLv999の恋をする", image: "covers/154965.jpg", popularity: 191572, isSequel: false, score: 7.7 },
    { titleZh: "我想成為影之強者！ 第二季", titleEn: "The Eminence in Shadow Season 2", titleJa: "陰の実力者になりたくて！ 2nd season", image: "covers/161964.jpg", popularity: 182680, isSequel: true, score: 8.2 },
  ],
  "2024": [
    { titleZh: "我獨自升級", titleEn: "Solo Leveling", titleJa: "俺だけレベルアップな件", image: "covers/151807.png", popularity: 416463, isSequel: false, score: 8.1 },
    { titleZh: "膽大黨", titleEn: "DAN DA DAN", titleJa: "ダンダダン", image: "covers/171018.jpg", popularity: 359486, isSequel: false, score: 8.3 },
    { titleZh: "怪獸8號", titleEn: "Kaiju No. 8", titleJa: "怪獣８号", image: "covers/153288.jpg", popularity: 265430, isSequel: false, score: 8.1 },
    { titleZh: "鬼滅之刃 柱訓練篇", titleEn: "Demon Slayer: Kimetsu no Yaiba Hashira Training Arc", titleJa: "鬼滅の刃 柱稽古編", image: "covers/166240.png", popularity: 258395, isSequel: true, score: 7.9 },
    { titleZh: "迷宮飯", titleEn: "Delicious in Dungeon", titleJa: "ダンジョン飯", image: "covers/153518.jpg", popularity: 212093, isSequel: false, score: 8.5 },
    { titleZh: "無職轉生 II ～到了異世界就拿出真本事～ 第2部分", titleEn: "Mushoku Tensei: Jobless Reincarnation Season 2 Part 2", titleJa: "無職転生Ⅱ ～異世界行ったら本気だす～ 第2クール", image: "covers/166873.png", popularity: 188234, isSequel: true, score: 8.3 },
    { titleZh: "不時輕聲地以俄語遮羞的鄰座艾莉同學", titleEn: "Alya Sometimes Hides Her Feelings in Russian", titleJa: "時々ボソッとロシア語でデレる隣のアーリャさん", image: "covers/162804.jpg", popularity: 187240, isSequel: false, score: 7.5 },
    { titleZh: "WIND BREAKER 防風少年", titleEn: "WIND BREAKER", titleJa: "WIND BREAKER", image: "covers/163270.jpg", popularity: 179504, isSequel: false, score: 7.7 },
    { titleZh: "Re:從零開始的異世界生活 第三季", titleEn: "Re:ZERO -Starting Life in Another World- Season 3", titleJa: "Re:ゼロから始める異世界生活 3rd season", image: "covers/163134.jpg", popularity: 178386, isSequel: true, score: 8.4 },
    { titleZh: "歡迎來到實力至上主義的教室 第三季", titleEn: "Classroom of the Elite Season 3", titleJa: "ようこそ実力至上主義の教室へ 3rd Season", image: "covers/146066.jpg", popularity: 176795, isSequel: true, score: 7.8 },
    { titleZh: "關於我轉生變成史萊姆這檔事 第三季", titleEn: "That Time I Got Reincarnated as a Slime Season 3", titleJa: "転生したらスライムだった件 第3期", image: "covers/156822.jpg", popularity: 172091, isSequel: true, score: 7.8 },
    { titleZh: "MASHLE 魔法少年 神覺者候補選拔考試篇", titleEn: "MASHLE: MAGIC AND MUSCLES Season 2", titleJa: "マッシュル-MASHLE- 神覚者候補選抜試験編", image: "covers/166610.jpg", popularity: 171940, isSequel: true, score: 7.8 },
    { titleZh: "我的英雄學院 第七季", titleEn: "My Hero Academia Season 7", titleJa: "僕のヒーローアカデミア 7", image: "covers/163139.jpg", popularity: 171900, isSequel: true, score: 8.2 },
    { titleZh: "為美好的世界獻上祝福！3", titleEn: "KONOSUBA -God's blessing on this wonderful world! 3", titleJa: "この素晴らしい世界に祝福を！３", image: "covers/136804.jpg", popularity: 170093, isSequel: false, score: 8.2 },
    { titleZh: "【我推的孩子】第二季", titleEn: "Oshi no Ko Season 2", titleJa: "【推しの子】第2期", image: "covers/166531.jpg", popularity: 168708, isSequel: true, score: 8.5 },
  ],
  "2025": [
    { titleZh: "我獨自升級 第二季 -Arise from the Shadow-", titleEn: "Solo Leveling Season 2 -Arise from the Shadow-", titleJa: "俺だけレベルアップな件 Season 2 -Arise from the Shadow-", image: "covers/176496.png", popularity: 285729, isSequel: true, score: 8.5 },
    { titleZh: "Gachiakuta", titleEn: "Gachiakuta", titleJa: "ガチアクタ", image: "covers/178025.jpg", popularity: 230912, isSequel: false, score: 8.2 },
    { titleZh: "膽大黨 第二季", titleEn: "DAN DA DAN Season 2", titleJa: "ダンダダン 第2期", image: "covers/185660.jpg", popularity: 210012, isSequel: true, score: 8.3 },
    { titleZh: "SAKAMOTO DAYS 坂本日常", titleEn: "SAKAMOTO DAYS", titleJa: "SAKAMOTO DAYS", image: "covers/177709.png", popularity: 205402, isSequel: false, score: 7.6 },
    { titleZh: "薰香花朵凜然綻放", titleEn: "The Fragrant Flower Blooms With Dignity", titleJa: "薫る花は凛と咲く", image: "covers/181444.jpg", popularity: 186657, isSequel: false, score: 8.5 },
    { titleZh: "藥師少女的獨語 第二季", titleEn: "The Apothecary Diaries Season 2", titleJa: "薬屋のひとりごと 第2期", image: "covers/176301.jpg", popularity: 185501, isSequel: true, score: 8.8 },
    { titleZh: "戀上換裝娃娃 第二季", titleEn: "My Dress-Up Darling Season 2", titleJa: "その着せ替え人形は恋をする Season 2", image: "covers/154768.jpg", popularity: 173116, isSequel: true, score: 8.2 },
    { titleZh: "一拳超人 第三季", titleEn: "One-Punch Man Season 3", titleJa: "ワンパンマン３", image: "covers/153800.jpg", popularity: 143714, isSequel: true, score: 5 },
    { titleZh: "怪獸8號 第二季", titleEn: "Kaiju No. 8 Season 2", titleJa: "怪獣８号 第２期", image: "covers/178754.jpg", popularity: 143647, isSequel: true, score: 7.8 },
    { titleZh: "光逝去的夏天", titleEn: "The Summer Hikaru Died", titleJa: "光が死んだ夏", image: "covers/177689.jpg", popularity: 129154, isSequel: false, score: 8.1 },
    { titleZh: "章魚嗶的原罪", titleEn: "Takopi's Original Sin", titleJa: "タコピーの原罪", image: "covers/185407.jpg", popularity: 128942, isSequel: false, score: 8.6 },
    { titleZh: "炎炎消防隊 參之章", titleEn: "Fire Force Season 3", titleJa: "炎炎ノ消防隊 参ノ章", image: "covers/149118.jpg", popularity: 122024, isSequel: true, score: 7.8 },
    { titleZh: "SPY×FAMILY 間諜家家酒 第三季", titleEn: "SPY x FAMILY Season 3", titleJa: "SPY×FAMILY Season 3", image: "covers/177937.jpg", popularity: 121865, isSequel: true, score: 8.2 },
    { titleZh: "我的英雄學院 最終季", titleEn: "My Hero Academia FINAL SEASON", titleJa: "僕のヒーローアカデミア FINAL SEASON", image: "covers/182896.jpg", popularity: 119438, isSequel: true, score: 8.7 },
    { titleZh: "LAZARUS 拉撒路", titleEn: "LAZARUS", titleJa: "ラザロ", image: "covers/167336.png", popularity: 108245, isSequel: false, score: 7 },
  ],
}

export default data

export const getAnimeTitle = (anime: AnimeItem, language: Language): string => {
  if (language === "en") return anime.titleEn
  if (language === "ja") return anime.titleJa
  return anime.titleZh
}
